### ISSUE TITLE
[torch-neuron] Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul'

### ISSUE THREAD

**Issue by Saief1999** [aws-neuron/aws-neuron-sdk#606] opened 2022-12-01 20:41 UTC
Hello everyone,

I'm trying to trace our custom model on an inf1 instance. Currently running into a compilation error. Would really appreciate your help.

### Setup and Packages

**Instance Type** : `inf1.2xlarge`

**AMI** : Amazon linux 2 , running a `uname -r` we get `5.10.149-133.644.amzn2.x86_64`

**Packages versions** : We followed the setup described here :  https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/quick-start/torch-neuron.html#torch-quick-start

We started by testing the tutorial offered by AWS here : https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-inferentia-pytorch-neuron.html  , It works fine.

For reference, this is what I get running a `pip list` on my virtual environment

```
...
tensorboard          1.15.0
tensorflow           1.15.5
tensorflow-estimator 1.15.1
torch                1.12.1
torch-neuron         1.12.1.2.5.8.0
torchvision          0.13.1
...
```

### Tracing

This is what I did

```python
        # self.model is a custom model extending torch.nn.Module
        # Loading the model
        self.model.load_state_dict(torch.load(self.model_path, "cpu"))

        # Converting inputs to tensors
        feats = torch.Tensor(feats)
        embeddings = torch.Tensor(embeddings)

        # Put model in evaluation state
        self.model.eval()

        # Tracing the Model
        model_neuron = torch.neuron.trace(self.model, example_inputs=(feats, embeddings))

       # This doesn't throw any errors.
       # model_jit = torch.jit.trace(self.model, example_inputs=(feats, embeddings))
```

### Error Logs

This is what I got running tracing on our model

```
INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 183, fused = 183, percent fused = 100.0%
WARNING:tensorflow:From /home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/ops/aten.py:2277: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::linear with inputs [<tf.Tensor 'aten_max/Max:0' shape=(24,) dtype=float32>, <tf.Tensor 'Linear_59/prim_Constant/Const:0' shape=(1, 24) dtype=float32>, None]
INFO:Neuron:Exception = Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$341; falling back to native python function call
ERROR:Neuron:Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].
Traceback (most recent call last):
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/convert.py", line 392, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/decorators.py", line 82, in trace
    transform_torch_graph_to_tensorflow(jit_trace, example_inputs, neuron_graph=func, **kwargs)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/decorators.py", line 583, in transform_torch_graph_to_tensorflow
    raise e
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/decorators.py", line 577, in transform_torch_graph_to_tensorflow
    tensor_outputs = local_func(op, *tensor_inputs)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/ops/aten.py", line 3474, in linear
    tensor_out = tf.matmul(input, tf.transpose(weight))
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 2754, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6136, in mat_mul
    name=name)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 183, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 7 [supported]
INFO:Neuron: => aten::add: 21 [supported]
INFO:Neuron: => aten::bmm: 7 [supported]
INFO:Neuron: => aten::cat: 8 [supported]
INFO:Neuron: => aten::detach: 1 [supported]
INFO:Neuron: => aten::expand: 7 [supported]
INFO:Neuron: => aten::layer_norm: 15 [supported]
INFO:Neuron: => aten::linear: 46 [supported]
INFO:Neuron: => aten::max: 1 [supported]
INFO:Neuron: => aten::relu: 8 [supported]
INFO:Neuron: => aten::repeat_interleave: 7 [supported]
INFO:Neuron: => aten::select: 2 [supported]
INFO:Neuron: => aten::size: 14 [supported]
INFO:Neuron: => aten::slice: 4 [supported]
INFO:Neuron: => aten::softmax: 7 [supported]
INFO:Neuron: => aten::squeeze: 7 [supported]
INFO:Neuron: => aten::tanh: 7 [supported]
INFO:Neuron: => aten::transpose: 7 [supported]
INFO:Neuron: => aten::unsqueeze: 7 [supported]
Traceback (most recent call last):
  File "trace.py", line 150, in <module>
    tracer.trace_model()
  File "trace.py", line 87, in trace_model
    model_neuron = torch.neuron.trace(self.model, example_inputs=(feats, embeddings))
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/convert.py", line 195, in trace
    cu.stats_post_compiler(neuron_graph)
  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/convert.py", line 503, in stats_post_compiler
    "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

> **Note** : Inside the model, We are using `Linear(24, 1, bias=False)` which seems to be related to the problem. Any help would be much appreciated.

**Comment by aws-owinop** [comment] 2022-12-02 00:06
Hi @Saief1999,
We are able to reproduce this issue. We will provide an update once we have a fix.

**Comment by aws-owinop** [comment] 2022-12-02 00:09
Hi Saief,

We are able to reproduce this issue on our end. We are currently working on a fix. We will update you once we have the fix ready.

Thanks,
Paul.

From: Saief Zneti ***@***.***>
Reply to: aws-neuron/aws-neuron-sdk ***@***.***>
Date: Thursday, 01 December 2022 at 12:42
To: aws-neuron/aws-neuron-sdk ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aws-neuron/aws-neuron-sdk] [torch-neuron] Cannot Trace Custom model for inference (Issue #606)


Hello everyone,

I'm trying to trace our custom model on an inf1 instance. Currently running into a compilation error. Would really appreciate your help.

Setup and Packages

Instance Type : inf1.2xlarge

AMI : Amazon linux 2 , running a uname -r we get 5.10.149-133.644.amzn2.x86_64

Packages versions : We followed the setup described here : https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/quick-start/torch-neuron.html#torch-quick-start

We started by testing the tutorial offered by AWS here : https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-inferentia-pytorch-neuron.html , It works fine.

For reference, this is what I get running a pip list on my virtual environment

...

tensorboard          1.15.0

tensorflow           1.15.5

tensorflow-estimator 1.15.1

torch                1.12.1

torch-neuron         1.12.1.2.5.8.0

torchvision          0.13.1

...

Tracing

This is what I did

        # self.model is a custom model extending torch.nn.Module

        # Loading the model

        self.model.load_state_dict(torch.load(self.model_path, "cpu"))



        # Converting inputs to tensors

        feats = torch.Tensor(feats)

        embeddings = torch.Tensor(embeddings)



        # Put model in evaluation state

        self.model.eval()



        # Tracing the Model

        model_neuron = torch.neuron.trace(self.model, example_inputs=(feats, embeddings))



       # This doesn't throw any errors.

       # model_jit = torch.jit.trace(self.model, example_inputs=(feats, embeddings))

Error Logs

This is what I got running tracing on our model

INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)

INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 183, fused = 183, percent fused = 100.0%

WARNING:tensorflow:From /home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/ops/aten.py:2277: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.

Instructions for updating:

Use tf.where in 2.0, which has the same broadcast rule as np.where

INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::linear with inputs [<tf.Tensor 'aten_max/Max:0' shape=(24,) dtype=float32>, <tf.Tensor 'Linear_59/prim_Constant/Const:0' shape=(1, 24) dtype=float32>, None]

INFO:Neuron:Exception = Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].

WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$341; falling back to native python function call

ERROR:Neuron:Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].

Traceback (most recent call last):

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op

    c_op = c_api.TF_FinishOperation(op_desc)

tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/convert.py", line 392, in op_converter

    item, inputs, compiler_workdir=sg_workdir, **kwargs)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/decorators.py", line 82, in trace

    transform_torch_graph_to_tensorflow(jit_trace, example_inputs, neuron_graph=func, **kwargs)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/decorators.py", line 583, in transform_torch_graph_to_tensorflow

    raise e

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/decorators.py", line 577, in transform_torch_graph_to_tensorflow

    tensor_outputs = local_func(op, *tensor_inputs)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/ops/aten.py", line 3474, in linear

    tensor_out = tf.matmul(input, tf.transpose(weight))

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper

    return target(*args, **kwargs)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 2754, in matmul

    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6136, in mat_mul

    name=name)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper

    op_def=op_def)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func

    return func(*args, **kwargs)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op

    attrs, op_def, compute_device)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal

    op_def=op_def)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__

    control_input_ops)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op

    raise ValueError(str(e))

ValueError: Shape must be rank 2 but is rank 1 for 'Linear_59/aten_linear/MatMul' (op: 'MatMul') with input shapes: [24], [24,1].

INFO:Neuron:Number of arithmetic operators (post-compilation) before = 183, compiled = 0, percent compiled = 0.0%

INFO:Neuron:The neuron partitioner created 1 sub-graphs

INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%

INFO:Neuron:Compiled these operators (and operator counts) to Neuron:

INFO:Neuron:Not compiled operators (and operator counts) to Neuron:

INFO:Neuron: => aten::Int: 7 [supported]

INFO:Neuron: => aten::add: 21 [supported]

INFO:Neuron: => aten::bmm: 7 [supported]

INFO:Neuron: => aten::cat: 8 [supported]

INFO:Neuron: => aten::detach: 1 [supported]

INFO:Neuron: => aten::expand: 7 [supported]

INFO:Neuron: => aten::layer_norm: 15 [supported]

INFO:Neuron: => aten::linear: 46 [supported]

INFO:Neuron: => aten::max: 1 [supported]

INFO:Neuron: => aten::relu: 8 [supported]

INFO:Neuron: => aten::repeat_interleave: 7 [supported]

INFO:Neuron: => aten::select: 2 [supported]

INFO:Neuron: => aten::size: 14 [supported]

INFO:Neuron: => aten::slice: 4 [supported]

INFO:Neuron: => aten::softmax: 7 [supported]

INFO:Neuron: => aten::squeeze: 7 [supported]

INFO:Neuron: => aten::tanh: 7 [supported]

INFO:Neuron: => aten::transpose: 7 [supported]

INFO:Neuron: => aten::unsqueeze: 7 [supported]

Traceback (most recent call last):

  File "trace.py", line 150, in <module>

    tracer.trace_model()

  File "trace.py", line 87, in trace_model

    model_neuron = torch.neuron.trace(self.model, example_inputs=(feats, embeddings))

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/convert.py", line 195, in trace

    cu.stats_post_compiler(neuron_graph)

  File "/home/ec2-user/shiva/myenv/lib64/python3.7/site-packages/torch_neuron/convert.py", line 503, in stats_post_compiler

    "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!

Note : Inside the model, We are using Linear(24, 1, bias=False) which seems to be related to the problem. Any help would be much appreciated.

**Comment by shebbur-aws** [comment] 2023-02-06 20:36
Hi @Saief1999, we have a fix and will be released in one of the upcoming releases for inf1.

**Closed** 2023-03-29 21:10 UTC
Labels: bug, Inf1, torch-neuron, pytorch
