### ISSUE TITLE
Different input batch sizes in compile cause different outputs

### ISSUE THREAD

**Issue by ukus04** [aws-neuron/aws-neuron-sdk#611] opened 2022-12-06 06:15 UTC
When I compiled with different input batch sizes,
- The size of the output neuron model parameter is different.
- Inference output of the models is different with the same input.

![image](https://user-images.githubusercontent.com/14154013/205835070-fc8b355f-4d4d-46bc-acec-65212e9e936d.png)
The result is `3.4064`

![image](https://user-images.githubusercontent.com/14154013/205835465-7c2141c8-7fd3-4385-b6e1-97066993775e.png)

I want to know why the input batch size in compile time causes the variation of the inference outputs.

**Comment by jeffhataws** [comment] 2022-12-06 19:43
Hello @ukus04,

The variation of inference outputs is expected behavior because different batch sizes can cause different transformations to occur in neuron-cc. Even though the underlying hardware operations may not be identical, the final results should be similar for the given floating point precision used. The error in individual values when comparing across batch sizes will be different but should be relatively small compared to the effects of mixed precision.

If the model does not meet your accuracy goals, check the [Mixed precision and performance-accuracy tuning (neuron-cc)](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/neuron-cc/mixed-precision.html) guide to tune your model accuracy.

**Comment by ukus04** [comment] 2022-12-07 01:11
Thanks for explanation!

**Comment by jeffhataws** [comment] 2022-12-08 15:59
@ukus04 thanks for filling the ticket. I will close it for now, but will be happy to look into any further issues you have.

**Closed by jeffhataws** 2022-12-08 15:59 UTC
