### ISSUE TITLE
torch-neuron compilation error: 'int' object has no attribute 'device'

### ISSUE THREAD

**Issue by altansnl** [aws-neuron/aws-neuron-sdk#605] opened 2022-11-29 09:38 UTC
i get the following error

```
Traceback (most recent call last):
  File "inf1_compile.py", line 73, in <module>
    model_neuron = torch.neuron.trace(model, example_inputs=[image])
  File "/home/altan/.pyenv/versions/inf1/lib/python3.7/site-packages/torch_neuron/convert.py", line 194, in trace
    neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
  File "/home/altan/.pyenv/versions/inf1/lib/python3.7/site-packages/torch_neuron/convert.py", line 409, in compile_fused_operators
    neuron_graph(*neuron_graph.example_inputs, op_converter=op_converter)
  File "/home/altan/.pyenv/versions/inf1/lib/python3.7/site-packages/torch_neuron/graph.py", line 198, in __call__
    self.run_op(op, unique_tensor_map, op_converter)
  File "/home/altan/.pyenv/versions/inf1/lib/python3.7/site-packages/torch_neuron/graph.py", line 209, in run_op
    outputs = op(*inputs)
  File "/home/altan/.pyenv/versions/inf1/lib/python3.7/site-packages/torch_neuron/graph.py", line 342, in __call__
    return self.func(self, *inputs)
  File "/home/altan/.pyenv/versions/inf1/lib/python3.7/site-packages/torch_neuron/native_ops/prim.py", line 46, in PythonOp
    return op.pyobj(*args, *op.scalar_args)
  File "/home/altan/.pyenv/versions/inf1/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 91, in forward
    ctx.input_device = input.get_device() if input.device.type != "cpu" else -1
AttributeError: 'int' object has no attribute 'device'
```
here is how I am trying to compile the model

```
    model = Model(opt, device)
    model = torch.nn.DataParallel(model).to(device)

    # load model
    print('loading pretrained model from %s' % opt.saved_model)
    model.load_state_dict(torch.load(opt.saved_model, map_location=device))

    image = torch.zeros([1, 1, 32, 100], dtype=torch.float32).to(device)
    text_for_pred = torch.LongTensor(1, opt.batch_max_length + 1).fill_(0).to(device)

    # Analyze the model - this will show operator support and operator count
    torch.neuron.analyze_model(model, example_inputs=[image])

    # Compile the model using torch.neuron.trace to create a Neuron model
    # that that is optimized for the Inferentia hardware
    model_neuron = torch.neuron.trace(model, example_inputs=[image])
```
my `example_inputs` should have a `.device` method since it's a tensor. not sure what I am doing wrong. can provide more information on request. 

the model i am trying to compile is from https://github.com/clovaai/deep-text-recognition-benchmark, with `ResNet-BiLSTM-Attn` model. and here is my pip freeze output:

```
absl-py==1.3.0
astor==0.8.1
attrs==22.1.0
certifi==2022.9.24
charset-normalizer==2.1.1
dataclasses==0.6
decorator==5.1.1
dmlc-nnvm==1.13.0.0+0
dmlc-topi==1.13.0.0+0
dmlc-tvm==1.13.0.0+0
exceptiongroup==1.0.4
future==0.18.2
gast==0.2.2
google-pasta==0.2.0
grpcio==1.50.0
h5py==2.10.0
idna==3.4
importlib-metadata==5.1.0
inferentia-hwm==1.13.0.0+0
iniconfig==1.1.1
islpy==2021.1+aws2021.x.80.0.bld0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.4.1
MarkupSafe==2.1.1
networkx==2.5
neuron-cc==1.13.5.0+7dcf000a6
numpy==1.18.5
opt-einsum==3.3.0
packaging==21.3
Pillow==9.3.0
pluggy==1.0.0
protobuf==3.20.1
pyparsing==3.0.9
pytest==7.2.0
requests==2.28.1
scipy==1.4.1
six==1.16.0
tensorboard==1.15.0
tensorflow==1.15.5
tensorflow-estimator==1.15.1
termcolor==2.1.1
tomli==2.0.1
torch==1.12.1+cu113
torch-neuron==1.12.1.2.5.8.0
torchaudio==0.12.1
torchvision==0.13.1+cu113
typing_extensions==4.4.0
urllib3==1.26.13
Werkzeug==2.2.2
wrapt==1.14.1
zipp==3.11.0
```

would appreciate any help! is it because i am compiling a model which has a `torch.nn.DataParallel` wrapper?

**Comment by altansnl** [comment] 2022-11-29 09:40
i'm aware that some of my operations are not supported, and most likely will change the model since having `cpu` execute some operations might not be optimal.

however, this error should be unrelated to that, since i can still run those operations in `cpu`.

**Comment by altansnl** [comment] 2022-11-29 10:09
and without the `torch.nn.dataparallel` wrapper, i get the following:

```
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument input_bias in method wrapper___thnn_fused_lstm_cell)
```

which is an unsupported operator, but ideally would not prevent the compilation.

**Comment by aws-owinop** [comment] 2022-11-29 19:30
Hi @altansnl,
The error you are running into appears to be caused by mixed usage of CPU/GPU allocated tensors. As a first step, could you make sure that both the inputs and model are moved to CPU prior to compilation? A good way to validate that a model will be able to be compiled for Inferentia is if you can run `torch.jit.trace` on your model successfully. Please try a normal trace after moving your model/inputs to CPU and share the output with us

**Comment by altansnl** [comment] 2022-11-30 10:20
`ResNet-BiLSTM-CTC` model ended up compiling fine and has 100% operator support. therefore i will probably not continue debugging this at the moment. 

if I have troubles compiling a model again i'll try to run `torch.jit.trace` on the model 👍 thanks for the tips.

**Comment by aws-owinop** [comment] 2022-11-30 16:32
Thank you @altansnl for the feedback, I will proceed to close this issue.

**Closed** 2022-11-30 16:32 UTC
Labels: Inf1, torch-neuron
