### ISSUE TITLE
HAL:aws_hal_tpb_pooling_write_profile failed programming the engine

### ISSUE THREAD

**Issue by paaksing** [aws-neuron/aws-neuron-sdk#607] opened 2022-12-02 22:29 UTC
I am attempting to deploy a model on Real-Time inference endpoint using `ml.inf1.xlarge` instances.

What does this even mean ? Google shows no results either.
![image](https://user-images.githubusercontent.com/58193352/205400231-e02443ca-9a2e-486e-a76f-0ab6a9667b06.png)
This is the dockerfile I am using:
```Dockerfile
FROM ubuntu:20.04

WORKDIR /usr/bin

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Upgrade installed packages
RUN apt-get -y update && apt-get -y upgrade && apt-get clean
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
    curl \
    gnupg \
    wget \
    python3-dev \
    python3-distutils \
    python3-setuptools \
    python3-pip \
    && python3 -m pip install pip

# Add neuron repository
RUN echo "deb https://apt.repos.neuron.amazonaws.com focal main" > /etc/apt/sources.list.d/neuron.list
RUN wget -qO - https://apt.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB | apt-key add -
RUN apt-get update -y && apt-get install aws-neuronx-dkms -y

# Sets up Path for Neuron tools
ENV PATH="/opt/bin/:/opt/aws/neuron/bin:${PATH}"

# Install dependencies
RUN pip3 install -U \
    torch==1.8.1 \
    torchvision==0.9.1 \
    torch-neuron==1.8.1.* \
    --extra-index-url="https://pip.repos.neuron.amazonaws.com"
COPY . .
RUN pip3 install -r requirements.txt

# One neuron core per gunicorn worker
ENV NEURON_RT_NUM_CORES 1
ENTRYPOINT ["./entrypoint.sh"]
```
`requirements.txt` only contains non-pytorch packages, `entrypoint` is simply a script to spawning the server.

**Comment by paaksing** [comment] 2022-12-02 23:53
The created endpoint is also stuck at creating for more than 40 minutes, the delete button is also disabled
![image](https://user-images.githubusercontent.com/58193352/205410471-c3b3e117-411b-4e44-bd1b-e0663f1e08d1.png)

**Comment by micwade-aws** [comment] 2022-12-03 00:39
@paaksing - We suspect the issue is with an incompatibility between latest Neuron SDK and the version of Neuron Driver used in Sagemaker Hosting.  

Please pin your version of torch-neuron to 1.8.1.2.3* for now.

I will update here again as soon as the Neuron Driver is updated in Sagemaker Hosting and it's safe to update to latest Neuron SDK on Sagemaker.

**Comment by paaksing** [comment] 2022-12-03 01:14
@micwade-aws The dockerfile is installing `aws-neuronx-dkms` (according to the docs for inference and latest version), which I think it's neuron 2.5, is it fine for me to keep that ?

**Comment by micwade-aws** [comment] 2022-12-03 01:54
Can't install aws-neuronx-dkms in your container as it contains a kernel driver. Kernel drivers must be installed on the underlying host of the container. Even if it does successfully "install", it's not actually doing anything. Remove that too please and don't add it back. 

Will clarify this on our install instructions.

**Comment by paaksing** [comment] 2022-12-03 02:19
@micwade-aws Ok I specified the `1.8.1.2.3.*` version and it seems to be working now, with these warnings, I am assuming that it's fine to ignore them for now as the operators I used is kept consistent since 2.3?
![image](https://user-images.githubusercontent.com/58193352/205417730-539083df-ab32-475c-9192-b39f4e67f3b2.png)
Thanks for the clarification about the `dkms`, will remove it.

**Comment by abhayaps** [comment] 2022-12-16 11:52
Hey Team, I am also facing similar issue
I am using https://github.com/aws/deep-learning-containers/blob/master/pytorch/inference/docker/1.12/py3/sdk2.5.0/Dockerfile.neuron docker
Is there any update on this

**Comment by zhazhn** [comment] 2022-12-19 09:24
+1 
I used one inf1.6xlarge, today I changed to inf1.2xlarge. After stop/start operation, I meet the same error with above.
I need the follow package.
torch-neuron              1.12.1.2.0.0.0
Please advice how to get it work? thanks.

**Comment by aws-vrnatham** [comment] 2022-12-20 23:25
Please update the aws-neuronx-dkms in host to version > 2.4.0. For update please following instructions [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/quick-start/torch-neuron.html).

**Comment by abhayaps** [comment] 2022-12-21 18:05
AFAIK we can't install aws-neuronx-dkms inside docker container as it is kernel level dependency. So this should be install by SageMaker on their host.

**Comment by jeffhataws** [comment] 2023-02-11 21:32
@abhayaps @zhazhn, do you still have a problem after updating aws-neuronx-dkms in host to version > 2.4.0?

**Comment by aws-rhsoln** [comment] 2023-03-13 15:52
Since we haven’t heard back in a while we are closing this issue, please reopen it if more support from us is needed.

**Closed by aws-rhsoln** 2023-03-13 15:52 UTC
Labels: runtime
