### ISSUE TITLE
Very high device memory utilization

### ISSUE THREAD

**Issue by czmrand** [aws-neuron/aws-neuron-sdk#744] opened 2023-09-18 11:31 UTC
When running a simple ViT model on trn1 with batch size 16, memory utilization is greater than 10 GB. 
Even when using 16-bit float, we are limited to batch size 32 (memory utilization 12.6 GB.
On the other hand, the same model is run with batch size of 128 (and < 16 GB utilization) on GPU (ec2 g5.xlarge).
Attaching training scripts and screen capture of neuron-top

[train_gpu.txt](https://github.com/aws-neuron/aws-neuron-sdk/files/12647275/train_gpu.txt)
[train_trn.txt](https://github.com/aws-neuron/aws-neuron-sdk/files/12647276/train_trn.txt)
![Screenshot 2023-09-18 143032](https://github.com/aws-neuron/aws-neuron-sdk/assets/78731618/0f35868d-01d0-42a0-9eab-71abe18d77f0)

**Comment by aws-rhsoln** [comment] 2023-09-21 01:35
Thank you for reporting the issue. After looking at the script, looks like you are running with 2 workers (data-parallel degree=2). The 12.6GB reported in neuron-top is actually a sum of 2 neuron-core memory. If you press enter after selecting ND 0, it should show per core memory, which in this case should come to 6.3GB. So each data-parallel worker is taking only 6.3GB which goes well as per your expectation of <10GB.

**Comment by czmrand** [comment] 2023-09-21 06:58
Hi @aws-rhsoln 
Thanks for the response. and apologies for the confusion.
I will try to be more precise.
When I run the script attached  ([train_trn.txt](https://github.com/aws-neuron/aws-neuron-sdk/files/12680978/train_trn.txt)) (on two Neuron Cores) I am limited to a batch size of 16 per core.
During compilation neuron-top shows utilization of 5.6 GB (out of 16 GB)  on each core.
![neuron-top1](https://github.com/aws-neuron/aws-neuron-sdk/assets/78731618/21da7367-f6a7-4fb5-ae1c-40230b4865ed)

During training the neuron-top shows utilization of 6.4 GB on each core.
![neuron-top2](https://github.com/aws-neuron/aws-neuron-sdk/assets/78731618/553efbd1-3d59-49b9-ab94-3ab06b0f8512)

Presumably, this should allow to double the batch size (to 32). However, when I try that compilation either stalls or crashes with the message attached:
[trn1-32-batch-error.txt](https://github.com/aws-neuron/aws-neuron-sdk/files/12681267/trn1-32-batch-error.txt)

On the other hand, when I run on a g5 GPU instance I am able to reach 128 batch size. And when I run with 16, I see less than 3 GB utilization:
![peak-memory-gpu](https://github.com/aws-neuron/aws-neuron-sdk/assets/78731618/cae7505a-836f-4b7d-8362-b32a691e68c7)

So my expectation is:
1. That per neuron core memory would be < 3GB. In fact, in should actually be significantly less than GPU since neuron uses bfloat16 internally.
2. We should be able to reach 128 batch size on each neuron core.... And certainly more than 16!!

Hope that was more clear.
TIA

**Comment by aws-taylor** [comment] 2023-10-04 19:33
Hello @czmrand,

 I was barely able to get batch=32 to compile on an instance. For the compiler crash you observed, you may be successful as long as no other memory intensive processes are running and/or you enable swap on the machine. For batch=64, I was able to reproduce the compiler crash. High memory utilization is an issue we're aware of and actively working to improve. You might have some success using the `-O0` optimization level as well, at the expense of performance.  (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/compiler/neuronx-cc/api-reference-guide/neuron-compiler-cli-reference-guide.html)
 
 We will continue to investigate the sources of these high memory utilizations and update you with our findings.
 
 -Taylor

**Comment by micwade-aws** [comment] 2023-10-22 17:03
Closing the ticket - please keep an eye on release notes for improvements in memory utilization.

**Closed by micwade-aws** 2023-10-22 17:03 UTC
