### ISSUE TITLE
Field number 0 is illegal when compile MarianMT model

### ISSUE THREAD

**Issue by zhazhn** [aws-neuron/aws-neuron-sdk#487] opened 2022-09-14 11:30 UTC
I followed notebook "Transformers MarianMT Tutorial" but met below issue.
environment should be correct:
tensorboard               1.15.0
tensorboard-plugin-neuron 2.4.0.0
tensorflow                1.15.5
tensorflow-estimator      1.15.1
tensorflow-neuron         1.15.5.2.3.0.0
termcolor                 2.0.1
tokenizers                0.9.4
tomli                     2.0.1
torch                     1.7.1
torch-neuron              1.7.1.2.3.0.0

error message is:
/home/ubuntu/inf1_venv/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:716: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert key_padding_mask is None or key_padding_mask.shape == (bsz, src_len)
/home/ubuntu/inf1_venv/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:718: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_weights.size() == (bsz * self.num_heads, tgt_len, src_len)
/home/ubuntu/inf1_venv/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:736: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_output.size() == (bsz * self.num_heads, tgt_len, self.head_dim)
/home/ubuntu/inf1_venv/lib/python3.7/site-packages/transformers/models/bart/modeling_bart.py:287: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if torch.isinf(x).any() or torch.isnan(x).any():
INFO:Neuron:There are 2 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 431, fused = 423, percent fused = 98.14%
INFO:Neuron:Number of neuron graph operations 944 did not match traced graph 814 - using heuristic matching of hierarchical information
WARNING:tensorflow:From /home/ubuntu/inf1_venv/lib/python3.7/site-packages/torch_neuron/ops/aten.py:1510: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:Neuron:Compiling function _NeuronGraph$203 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/inf1_venv/bin/neuron-cc compile /tmp/tmpfy6durou/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpfy6durou/graph_def.neff --io-config {"inputs": {"0:0": [[1, 32, 512], "float32"], "1:0": [[1, 32], "bool"]}, "outputs": ["BartEncoder_1/aten_transpose_1/transpose:0"]} --verbose 35'
..
Compiler status PASS
INFO:Neuron:skip_inference_context for tensorboard symbols at /home/ubuntu/inf1_venv/lib/python3.7/site-packages/torch_neuron/tensorboard.py:305 tb_parse
INFO:Neuron:Number of neuron graph operations 944 did not match traced graph 814 - using heuristic matching of hierarchical information
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 431, compiled = 423, percent compiled = 98.14%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 1 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 100.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 78
INFO:Neuron: => aten::add: 48
INFO:Neuron: => aten::bmm: 12
INFO:Neuron: => aten::contiguous: 24
INFO:Neuron: => aten::dropout: 25
INFO:Neuron: => aten::layer_norm: 12
INFO:Neuron: => aten::masked_fill: 6
INFO:Neuron: => aten::matmul: 36
INFO:Neuron: => aten::mul: 30
INFO:Neuron: => aten::silu: 6
INFO:Neuron: => aten::size: 24
INFO:Neuron: => aten::softmax: 6
INFO:Neuron: => aten::t: 36
INFO:Neuron: => aten::transpose: 32
INFO:Neuron: => aten::unsqueeze: 12
INFO:Neuron: => aten::view: 36
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::ScalarImplicit: 1 [supported]
INFO:Neuron: => aten::add: 1 [supported]
INFO:Neuron: => aten::arange: 1 [supported]
INFO:Neuron: => aten::embedding: 2 [not supported]
INFO:Neuron: => aten::eq: 1 [supported]
INFO:Neuron: => aten::mul: 1 [supported]
INFO:Neuron: => aten::size: 1 [supported]
INFO:Neuron:skip_inference_context for tensorboard symbols at /home/ubuntu/inf1_venv/lib/python3.7/site-packages/torch_neuron/tensorboard.py:305 tb_parse
INFO:Neuron:Number of neuron graph operations 27 did not match traced graph 29 - using heuristic matching of hierarchical information
Traceback (most recent call last):
  File "infer.py", line 232, in <module>
    max_decoder_length=max_decoder_length
  File "infer.py", line 130, in trace
    self.encoder = torch_neuron.trace(encoder, inputs)
  File "/home/ubuntu/inf1_venv/lib/python3.7/site-packages/torch_neuron/convert.py", line 200, in trace
    torch_script = maybe_determine_names_from_tensorboard(neuron_graph, example_inputs, **kwargs)
  File "/home/ubuntu/inf1_venv/lib/python3.7/site-packages/torch_neuron/convert.py", line 531, in maybe_determine_names_from_tensorboard
    metaneff.ParseFromString(metaneff_bytes)
  File "/home/ubuntu/inf1_venv/lib/python3.7/site-packages/google/protobuf/message.py", line 202, in ParseFromString
    return self.MergeFromString(serialized)
  File "/home/ubuntu/inf1_venv/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 1128, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/ubuntu/inf1_venv/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 1178, in InternalParse
    raise message_mod.DecodeError('Field number 0 is illegal.')
google.protobuf.message.DecodeError: Field number 0 is illegal.

**Comment by zhazhn** [comment] 2022-09-14 11:31
protobuf version is less than 4, my environment is:
protobuf==3.20.2

**Comment by mrnikwaws** [comment] 2022-09-14 14:22
Hi @zhazhn,

Can you please confirm that you are using transformers==4.0.1 as specified in the notebook (https://github.com/aws-neuron/aws-neuron-sdk/blob/master/src/examples/pytorch/transformers-marianmt.ipynb)?  Because this tutorial depends on specific code changes the exact version is important.

Also can I confirm that you also need tensorflow-neuron in your environment?  Typically for a regular torch-neuron environment tensorflow ~= 1.15 is needed, but tensorflow-neuron is not.  This is likely *not* the root cause, but if the problem persists with these constraints I'll be working on keeping the test environment simple.

**Comment by mrnikwaws** [comment] 2022-09-14 16:59
Hi @zhazhn,

Further to the last message we have been able to reproduce your issue, this (new) version of protobuf creates a problem.  Please do the following:

```
pip install protobuf==3.20.1
```

This should resolve your issue.

**Comment by zhazhn** [comment] 2022-09-15 01:02
Hello @mrnikwaws,
You are correct.
The protobuf version should be 3.20.1.
Any chance to update this notebook and Neuron SDK docs. 
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/transformers-marianmt.html

Thanks a lot.

**Comment by mrnikwaws** [comment] 2022-09-15 15:37
Hi @zhazhn,

We have the notebook change in review at the moment, and hope to update it soon.  Since it looks like you are unblocked I'll plan to close this issue.

**Closed** 2022-09-19 18:28 UTC
