### ISSUE TITLE
torch.jit.load sometimes fails due to an allocation error

### ISSUE THREAD

**Issue by DHdroid** [aws-neuron/aws-neuron-sdk#625] opened 2023-01-09 07:45 UTC
## Problem

- When trying to load multiple neuron-compiled models, `torch.jit.load` randomly fails due to an allocation error
    - The workaround I found is to keep retrying until loading is successfully done.
- This error appears more often when I try to use torch-neuron with nvidia Triton.

## Environment
- Instance type: Inf1.2xlarge
- os: Ubuntu 20.04 LTS
- python version: 3.7.15
- libraries:
    - torch==1.11.0
    - torch-neuron==1.11.0.2.5.8.0
    - torchvision==0.12.0

## Code to reproduce
Here are the scripts I used to reproduce errors.

1. `compile.py`
    
    ```python
    import torch
    import torch.neuron
    from torchvision import models
    
    if __name__ == "__main__":
        model = models.resnet50(pretrained=True)
        model.eval()
        image = torch.zeros([4, 3, 224, 224], dtype=torch.float32)
        model_neuron = torch.neuron.trace(model,
                                          example_inputs=[image],
                                          dynamic_batch_size=True,
                                          strict=False,
                                          compiler_args=["--fast-math", "none"])
        model_neuron.save("resnet50.pt")
    ```
    
2. `validate.py`
    
    ```python
    import torch
    import torch.neuron
    
    def load_model_with_retries(model_path):
        loaded = False
        while not loaded:
            try:
                model = torch.jit.load(model_path)
            except:
                pass
            else:
                loaded = True
        return model
    

    def test_load_n_models(n, load_fn, model_path):
        model_list = []
        for i in range(n):
            try:
                model_list.append(load_fn(model_path))
            except:
                pass
        print(f"Load: total {len(model_list)}/{n} models are loaded")
        return
    

    def test_load_n_models_m_times(m, n, load_fn, model_path="resnet50.pt"):
        for _ in range(m):
            test_load_n_models(n, load_fn, model_path)
            
            
    if __name__ == "__main__":
        print("Testing Naive Load...")
        test_load_n_models_m_times(m=5, n=112, load_fn=torch.jit.load)
        print("Testing Load with Retries...")
        test_load_n_models_m_times(m=5, n=112, load_fn=load_model_with_retries)
    ```
    

When I ran the following commands, I got the result below:   

```bash
$ python compile.py
$ python validate.py > output.log
$ cat output.log
```

Result:

```shell
Testing Naive Load...
Load: total 112/112 models are loaded
Load: total 109/112 models are loaded
Load: total 106/112 models are loaded
Load: total 105/112 models are loaded
Load: total 101/112 models are loaded
Testing Load with Retries...
Load: total 112/112 models are loaded
Load: total 112/112 models are loaded
Load: total 112/112 models are loaded
Load: total 112/112 models are loaded
Load: total 112/112 models are loaded
```

The result says that `torch.jit.load` sometimes fails even if there’s available memory left and retrying solves the problem.  I also checked that there was enough memory using `neuron-top` while I was getting these errors.

## Note
When I removed the `try-except` clause from the `test_load_n_models` function in `validate.py`, I got this error:

```
Traceback (most recent call last):
  File "validate.py", line 34, in <module>
    test_load_n_models_m_times(m=5, n=112, load_fn=torch.jit.load)
  File "validate.py", line 29, in test_load_n_models_m_times
    test_load_n_models(n, load_fn, model_path)
  File "validate.py", line 20, in test_load_n_models
    model_list.append(load_fn(model_path))
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
    script_module = jit_load(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/jit/_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: Could not load the model status=4 message=Allocation Failure
```

Also, system errors appear on `stderr` :
```
2023-Jan-09 07:08:11.0110 371092:371092 ERROR  TDRV:dmem_alloc_internal                     Failed to alloc HOST memory: 640320
2023-Jan-09 07:08:11.0142 371092:371092 ERROR  TDRV:dml_dump                                Wrote nrt memory alloc debug info to /tmp/nrt_mem_log_device_0_63bbbd5b.csv
2023-Jan-09 07:08:11.0142 371092:371092 ERROR  TDRV:tensor_allocate                         Failed to allocate 640320 bytes on HOST for tensor strided_slice8:0.
2023-Jan-09 07:08:11.0142 371092:371092 ERROR  TDRV:kbl_tensor_create_host_tensor_cache_from_kbinFailed to create cached host tensor strided_slice8:0
2023-Jan-09 07:08:11.0142 371092:371092 ERROR  NMGR:dlr_kelf_stage                          Failed to create host tensor set cache at index 1
2023-Jan-09 07:08:11.0142 371092:371092 ERROR  NMGR:stage_kelf_models                       Failed to stage graph: kelf-a.json to NeuronCore
2023-Jan-09 07:08:11.0142 371092:371092 ERROR  NMGR:kmgr_load_nn_post_metrics               Failed to load NN: 1.13.5.0+7dcf000a6-/tmp/tmpewt3nwaw, err: 4
```

**Comment by jluntamazon** [comment] 2023-01-09 17:53
The allocation failure happens due to _host_ memory utilization. A failure can occur in the case that there is currently not enough CPU memory to perform a model load. External changes in memory utilization can cause this to occur. This can also occur in isolation since `torch-neuron` will attempt to unload unused data over time. The final few allocations may be failing because you are observing boundary conditions when you are near the limits of host memory. If you have observed this in a deployment scenario let us know.

**Comment by DHdroid** [comment] 2023-01-10 03:50
Thanks for your kind reply!
I also checked `Host Memory` through `neuron-top` while running the scripts above, but it seems that there is enough memory space left. Would you mind double-checking if it is usual behavior?
<img width="740" alt="image" src="https://user-images.githubusercontent.com/43927732/211457462-52461f18-af39-443d-84a4-9c9c5db5e051.png">

**Comment by DHdroid** [comment] 2023-01-10 08:48
I found two things:
1. Whenever I call `test_load_n_models`, memory utilization increases. And it never decreases back even after it is finished. I checked this by calling `sleep` after the function call.
2. The allocation error occurs even if there is available memory left. In my case, I got the errors though 7GB/16GB was in use.

**Comment by micwade-aws** [comment] 2023-01-13 03:10
Hi @DHdroid 

Just to clarify, neuron-top is reporting out memory and utilization as it pertains to applications utilizing Neuron Devices only.  It does not account for other applications running on the system that might be consuming memory.  When executing on an inf1.2xlarge, there’s typically 15GB of free host memory after the OS takes one GB for itself.

The model/memory unloading will not happen in your test code until the program is out of the scope these variables/models were loaded in. This may explain why the memory doesn’t appear to free when you run sleep. There are a few ways to offload an unused model to free up memory. A model is off-loaded when the process using the NeuronCore is terminated. If you want to keep the process alive and off-load the model within Python, you can call del on the model variable and it should clean up the resources (normal garbage collection should deallocate the model as well when it goes out of scope).

Before running your experiment, you can use free -h to measure the amount of free host memory on your instance. While your program is running, you can run htop in a separate terminal to monitor the host memory usage as each new model is loaded.

**Comment by DHdroid** [comment] 2023-01-13 05:54
Hi @micwade-aws,

Thank you for your clarification. I have tested the `sleep` function after the model goes out of scope, as well as manually calling `gc.collect()` to ensure proper garbage collection. Despite these efforts, I am still observing a memory leak, as the memory utilization does not decrease back to normal levels.

Additionally, I have used the `htop` tool to monitor memory usage (like what you suggested) and have identified the memory leak. Furthermore, I have discovered that an allocation error occurs even when there is available memory space remaining.

I am currently experiencing difficulty with this issue in our production code, specifically within our Triton Inference Server. I kindly request your assistance in addressing this issue as it occurs frequently.

**Comment by micwade-aws** [comment] 2023-01-13 13:34
@DHdroid  I was not able to reproduce this using the code and config info above, but maybe I'm missing something. Does the memory free after calling del on the model variable? Does it free after exiting the test program at all, or constantly increasing each time the validate script is run?

Do you mind posting more details on the software config and your EC2 instance id to help me reproduce what you're seeing?  Here's some commands to help collect this info:

```
apt list --installed | grep neuron
uname -r
cat /proc/cmdline
pip list | grep neuron

wget -q -O - http://169.254.169.254/latest/meta-data/instance-id

```

Any other software that may be installed and contributing to the issue would also be helpful for reproducing.

I will try again with any additional config info you provide. If I still can't reproduce the problem, we'll keep digging.

**Comment by DHdroid** [comment] 2023-01-14 16:47
Hi @micwade-aws!
Thank you for your kind reply :)
1. Memory (host memory) frees after exiting the program. However, it keeps increasing while the validate script is running. Memory usage increases whenever `test_load_n_models` is called and doesn't decrease back to normal levels even when the function call is finished.
2. I found that this problem is severe only when the model is compiled with non-default options like in `compile.py` (in my first comment). When I tested `validate.py` with `resnet50` compiled with default options, it seems that there is almost no memory leak.
3. The details for my EC2 instance:
```
apt list --installed | grep neuron
aws-neuronx-dkms/unknown,now 2.6.33.0 amd64 [installed]
aws-neuronx-tools/unknown,now 2.6.1.0 amd64 [installed]
```
```
uname -r
5.15.0-1026-aws
```
```
cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.15.0-1026-aws root=PARTUUID=3cb2726b-fe11-46b3-92c8-9a79050adc69 ro console=tty1 console=ttyS0 nvme_core.io_timeout=4294967295 panic=-1
```
```
pip list | grep neuron
neuron-cc                          1.13.5.0+7dcf000a6
torch-neuron                       1.11.0.2.5.8.0
```
```
wget -q -O - http://169.254.169.254/latest/meta-data/instance-id
i-079a4dba2a7743327
```

If you can't still reproduce my issue, let me know. Maybe I can record a video of shell where the scripts are being executed. Thanks!

**Comment by DHdroid** [comment] 2023-01-16 09:46
Update)
 I found out that the allocation error occurs because a large amount of memory is in use for `buff/cache`, resulting in a lack of host memory. Through `top`, I could see that my EC2 instance had high `buff/cache` memory usage so that `free` memory was insufficient. To resolve this, I tried adding `os.system("sudo sh -c \"echo 3 > /proc/sys/vm/drop_caches\"")` before every model load, and it successfully solves the problem by clearing the cache memory.

Though the allocation error is resolved, I'm not sure if it's a good practice to add cache clearing code(which needs superuser) in production. I think the expected behavior when `free` memory is insufficient due to `buff/cache` memory is that os should automatically free some of `buff/cache` memory to secure enough memory.

**Comment by josebenitezg** [comment] 2023-01-16 14:18
Hi! I am facing the same problem, after a few minutes of running I have a large memory used even tough I am not making any inference

**Comment by awsilya** [comment] 2023-01-18 19:18
@DHdroid I'm curious what was the size of buff/cache.

Each model load consumes host memory in addition to device memory.  For example on inf1 I/O tensors are allocated in host memory.   A model footprint is affected by I/O size and how many times the model is loaded.

It's not surprising that by freeing some host memory you were able to load a model a few more times.

**Comment by awsilya** [comment] 2023-01-20 23:16
@DHdroid, I'm going to close this issue.  If you need further help feel free to reopen.

**Closed by awsilya** 2023-01-20 23:16 UTC
Labels: Inf1, torch-neuron, runtime

**Comment by Mihir-Gajera1** [comment] 2023-06-01 20:58
@DHdroid  did you able to find any other workaround for this issue? I am getting the same allocation error in production on inf1.2xlarge nodes and after some time when the k8s pod restarts multiple times, the issue is getting resolved automatically.

**Comment by Mihir-Gajera1** [comment] 2023-06-04 23:02
@awsilya @micwade-aws  can you help here?
