### ISSUE TITLE
Dynamic batching in inference doesn't work when embedding layers are included

### ISSUE THREAD

**Issue by ukus04** [aws-neuron/aws-neuron-sdk#609] opened 2022-12-05 03:24 UTC
Our team's model is based on ViT and it has embedding layers, and the `forward` fucntion of the model takes a input of shape (1, 3, 224, 224). 

When we compile our model to neuron model with batch size 2, `--io-config flag` is set as `{"inputs": {"0:0": [[2, 3, 224, 224], "float32"], "1:0": [[1, 197, 768], "float32"], ...}`.

It's weird that another input is recognized and its batch size is not set as 2. 

Because of that, dynamic batching fails even though we compile the model with `dynamic_batch_size=True`

We want to know why unintended input is set. And we share test results for compiling some models.

Same issue reported
- CLIPModel.from_pretrained("openai/clip-vit-base-patch16").vision_model 

Not reported
- BERT based model

In case of CLIP, the issue does not occur, when`self.positional_embedding` related codes are commented.
```python
class CLIPVisionEmbeddings(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed_dim = 768
        self.image_size = 224
        self.patch_size = 16

        self.class_embedding = nn.Parameter(torch.randn(self.embed_dim))

        self.patch_embedding = nn.Conv2d(
            in_channels=3, out_channels=self.embed_dim, kernel_size=self.patch_size, stride=self.patch_size, bias=False
        )

        self.num_patches = (self.image_size // self.patch_size) ** 2
        self.num_positions = self.num_patches + 1
        self.position_embedding = nn.Embedding(self.num_positions, self.embed_dim)
        self.register_buffer("position_ids", torch.arange(self.num_positions).expand((1, -1)))

    def forward(self, pixel_values: torch.FloatTensor) -> torch.Tensor:
        batch_size = pixel_values.shape[0]
        patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, width, grid, grid]
        patch_embeds = patch_embeds.flatten(2).transpose(1, 2)

        class_embeds = self.class_embedding.expand(batch_size, 1, -1)
        embeddings = torch.cat([class_embeds, patch_embeds], dim=1)
        embeddings = embeddings + self.position_embedding(self.position_ids)
        return embeddings 
```

**Comment by aws-owinop** [comment] 2022-12-05 17:35
Hi @ukus04,
The reason you’re seeing a second input in the IO config is due to partitioning - it’s likely that the Neuron subgraph is created in such a way that it has multiple inputs. This isn’t an issue, it’s just a common result of partitioning.
The error you’re seeing is likely caused by an issue in our partitioner. Models that contain unsupported operators, such as `aten::embedding`, are partitioned to run on CPU. During partitioning, additional operators, such as `aten::size` are also sent to CPU. However, there’s an issue in our partitioner where the input batch sizes are not properly recorded at inference time when `aten::size` operators are sent to CPU. This is [known issue](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/torch/torch-neuron/torch-neuron.html#dynamic-batching) and is being worked on.

**Comment by ukus04** [comment] 2022-12-06 02:53
Thank you for your answer.

I checked the compile log, we have an unsupported operator(`aten::embedding`) and only one `aten::embedding`.
And there are many `aten::size` in compiled operators.

The neuron partitioner created 1 sub-graph

In the inference time, the error was different from that of known issue.

```python
<ipython-input-5-d5ac564e7db0> in _benchmark(model, example_inputs, batch_size, latencies, tpss, num_infers, latency_percentile)
     40 ) -> None:
     41     # The first inference loads the model so exclude it from timing
---> 42     _ = model(*example_inputs)
     43
     44     latency = []

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_neuron/runtime/___torch_mangle_943.py", line 12, in forward
    _0 = torch.embedding(CONSTANTS.c0, CONSTANTS.c1)
    model = _NeuronGraph_6.model
    _1 = ops.neuron.forward_v2_1([argument_1, _0], model)
         ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _1

Traceback of TorchScript, original code (most recent call last):
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/decorators.py(381): forward
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch/nn/modules/module.py(1098): _slow_forward
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch/nn/modules/module.py(1110): _call_impl
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/graph.py(580): __call__
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/graph.py(209): run_op
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/graph.py(198): __call__
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/runtime.py(69): forward
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch/nn/modules/module.py(1098): _slow_forward
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch/nn/modules/module.py(1110): _call_impl
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch/jit/_trace.py(958): trace_module
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch/jit/_trace.py(741): trace
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/tensorboard.py(324): tb_parse
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/tensorboard.py(550): tb_graph
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/decorators.py(491): maybe_generate_tb_graph_def
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/convert.py(552): maybe_determine_names_from_tensorboard
/home/user/.miniconda3/envs/project/lib/python3.8/site-packages/torch_neuron/convert.py(211): trace
compile.py(52): compile_pytorch
compile.py(77): <module>
RuntimeError: Inconsistent batch sizes found on inputs. All batch tensors must have the same dim 0 size.
	Input tensor #0 shape: 2 3 224 224
	Input tensor #1 shape: 1 197 768
```	
	
In the compile log, there was some warnings.
```
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz * self.num_heads, tgt_len, src_len):
```

So we have some questions.
1. Our runtime error is different from that of known issue. Could you please recheck the issue is a known issue?
2. The neuron partitioner created 1 sub-graph for our model. When the model contains unsupported operators, is it correct that 1 sub-graph is created? Is 1 sub-graph is partitioned to two parts(CPU and NeuronCore)?
3. You said `aten::size` are sent to CPU, but it is supported operator for neuron. I could not understand why `aten::size` is not sent to NeuronCore.

**Comment by hannanjgaws** [comment] 2022-12-06 21:33
We were able to reproduce the error you’re seeing. The easiest way to fix this issue is to compile `aten::embedding` instead of partitioning it to CPU. This can be accomplished by using the `fallback=False` flag during compilation to compile all operators in your model:

```
traced = torch_neuron.trace(model, example, dynamic_batch_size=True, fallback=False)
```

Note that this model is a special case where the positional embedding table is relatively small. Embedding operator support is disabled by default because there are many cases where moving this to device causes worse performance.

Can you retry compiling your model using `fallback=False` to see if it resolves the error you’re seeing?

1/ The error you are encountering is also a known issue. The latest torch-neuron release has additional debug information 
when this invalid dynamic batching configuration is encountered.

2/ The number of subgraphs created depends on the number of unsupported operators as well as where the unsupported operators occur within in the model. There is no easy heuristic to determine how many subgraphs will be created without running the torch-neuron partitioner. In general, having fewer subgraphs is better because it enables the compiler to perform more optimizations and reduces I/O bandwidth between CPU and the NeuronCores.

3/ Depending on the model structure, some supported operators may be run on CPU. This can happen because the torch-neuron partitioner tries to minimize the number of small subgraphs that are created. This occasionally results in supported operators running on CPU instead of being compiled into an additional small subgraph.

**Comment by ukus04** [comment] 2022-12-07 03:10
Oh, when I tested with `fallback=False` dynamic batching works. Thanks.

Will `aten::embedding` be supported officially and optimized for performance someday?

**Comment by hannanjgaws** [comment] 2022-12-07 17:42
Glad to hear you were able to fix the issues you were encountering!

It is unlikely that we will enable embeddings by default on Inf1. However, we are looking into ways to automatically enable embeddings for certain situations when compiling it on Neuron will be advantageous. These changes will likely come in a future release.

We will close this issue because you were able to resolve the issues in this ticket. Please feel free to open a new ticket if you encounter any other issues using Neuron in the future.

**Closed by hannanjgaws** 2022-12-07 17:42 UTC
Labels: bug, Inf1
