### ISSUE TITLE
Error: MPMD detected but reload is not supported yet

### ISSUE THREAD

**Issue by wfckl789** [aws-neuron/aws-neuron-sdk#882] opened 2024-05-04 09:14 UTC
Hi, I found the error `MPMD detected but reload is not supported yet` will occur if I open `Eager Debug Mode` for a model trained in neuron distributed environment where dp=1, tp=8, pp=4. Could you help check this issue? **Thanks so much!**

![image](https://github.com/aws-neuron/aws-neuron-sdk/assets/42508752/79763642-1ea9-4356-b4f8-4055fadd0de3)

I attach related scripts here and you can simply run `./run_simple_model_tp_pp.sh ` after download them.

[scripts.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/15209167/scripts.zip)

Environment information:

EC2 Instance: trn1.32.xlarge

OS: Ubuntu 20.04

Neuron Pytorch: Latest 2.18

**Comment by aws-rhsoln** [comment] 2024-05-04 20:01
Its a duplicate of this issue: https://github.com/aws-neuron/neuronx-distributed/issues/21 . Closing this one

**Closed by aws-rhsoln** 2024-05-04 20:01 UTC
