### ISSUE TITLE
Segfault + kernel tainted when performing (sd) inference using inf2/neuronx within a container 

### ISSUE THREAD

**Issue by oOraph** [aws-neuron/aws-neuron-sdk#725] opened 2023-08-18 12:19 UTC
I've provided all the details to reproduce the issue in the following repo:

https://github.com/oOraph/inf2_scripts

More specifically the following file:
https://github.com/oOraph/inf2_scripts/blob/main/reproduce_issue

the issue was first observed while performing inference on EKS on inf2.8xlarge nodes with AL2 images. I was then able to reproduce it with docker on an ec2 standalone instance as well

logs observed can be found here:
https://github.com/oOraph/inf2_scripts/tree/main/logs

Sum up to reproduce:
perform some inference task on a neuron within a container while monitoring the neuron state both inside and outside the container with neuron-top. Not sure how all this is related, but everytime the issue gets triggered, this was the situation

**Comment by aws-tcanepa** [comment] 2023-08-22 00:29
Issues are resolved in Neuron 2.12.1

Release notes:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#id4

Details on the two issues:

First issue is a contiguous physical page (memory) allocation failure during neuron runtime initialization causing a kernel Taint.  Basically Neuron is asking for a chunk of contiguous physical memory during initialization and the kernel doesn’t have anything available.

Why is this happening?

The size of AI containers and associated data are getting so large that they are causing the Kernel’s page cache to fragment host physical memory during container deployment, reducing the number of large contiguous memory buffers available for drivers and the kernel to use.  This has only been observed on memory constrained systems.

While the condition is temporary since the kernel reclaims pages from the page cache and compacts memory to replenish the contiguous memory buffers, the condition can persist long enough to prevent model load if a model is loaded immediately after the container is deployed.

Solution:

The Neuron driver has a reserve pool of physically continuous memory buffers.  We’ve reduced the size of our contiguous allocations so that the buffers so that the allocation requests can always be satisfied from the reserve pool.

The second issue is caused by an interaction between Neuron cores on the same Neuron device when one core is being reset, resulting in a DMA timeout.

**Comment by jluntamazon** [comment] 2023-08-22 18:03
I am closing this issue since it should be resolved with the 2.12 software update

**Closed by jluntamazon** 2023-08-22 18:03 UTC
