### ISSUE TITLE
YoloR neuron model has different accuracy compared to pytorch model

### ISSUE THREAD

**Issue by alejoGT1202** [aws-neuron/aws-neuron-sdk#437] opened 2022-06-28 14:29 UTC
Hello, I was able to convert the my yoloR weights using the information provided [here](https://github.com/aws/aws-neuron-sdk/issues/402). However, when I compared both models the results using the regular pytorch model are better compared to the one using torch-neuron. I also tried to used different configurations of parameters mentioned [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-cc/command-line-reference.html) but I see no improvement in the accuracy. Is there any other approach I should try to get the same performance as the one that runs on GPU?

Thanks for the help.

**Comment by jeffhataws** [comment] 2022-06-30 20:48
Thanks @alejoGT1202, we will take a look.

**Comment by hannanjgaws** [comment] 2022-07-08 21:21
Hi @alejoGT1202, we have been unable to reproduce significant accuracy issues for the YoloR model on Neuron. Using the `horses.jpg` example in the YoloR repository, we see no misclassification and minimal differences in the bounding boxes:

Neuron:
```
Boxes:
tensor([[1.00000e+00, 9.67500e+01, 1.05500e+02, 2.05250e+02],
        [1.44125e+02, 1.06250e+02, 1.97875e+02, 1.73750e+02],
        [7.72500e+01, 9.62500e+01, 1.40750e+02, 1.81750e+02],
        [1.25000e-01, 9.15000e+01, 5.16250e+01, 1.80500e+02]])

Classes:
tensor([17, 17, 17, 17])
```
CPU:
```
Boxes:
tensor([[1.27384e+00, 9.68708e+01, 1.05381e+02, 2.05727e+02],
        [1.44108e+02, 1.05776e+02, 1.97879e+02, 1.73561e+02],
        [7.80150e+01, 9.72486e+01, 1.41456e+02, 1.81188e+02],
        [1.30968e-01, 9.18810e+01, 5.16356e+01, 1.80621e+02]])

Classes:
tensor([17, 17, 17, 17])
```
For the bounding boxes, we see some difference:
```
Greatest absolute difference: 0.99859619140625 at index (2, 1) (up to 1e-05 allowed)
Greatest relative difference: 0.27384185791015625 at index (0, 0) (up to 0.0001 allowed)
```
This relative difference may seem high, but the box coordinates are in the range of the image size (0-255). If you look at the worst performing coordinate, this is 1.0 vs 1.27, which does not seem significant.

Are you able to provide a sample input that triggers the accuracy issues you’re observing?

**Comment by alejoGT1202** [comment] 2022-07-12 12:48
Hi @hannanjgaws I'm using the following [image](https://www.latimes.com/science/story/2020-11-20/face-masks-didnt-stop-coronavirus-spread-in-danish-clinical-trial) with my  custom trained face-body weights using the crowd human dataset. Here I'm attaching the results of GPU vs Neuron:

GPU: 
```
[tensor([[9.58000e+02, 2.83750e+02, 1.28000e+03, 8.73000e+02, 9.62891e-01, 0.00000e+00],
        [4.95250e+02, 2.46250e+02, 8.77000e+02, 8.74000e+02, 9.57520e-01, 0.00000e+00],
        [8.75000e-01, 3.71000e+02, 3.19500e+02, 8.75000e+02, 9.43359e-01, 0.00000e+00],
        [9.58500e+02, 2.16625e+02, 1.04900e+03, 3.35500e+02, 9.26270e-01, 1.00000e+00],
        [8.89500e+02, 2.14250e+02, 1.14400e+03, 8.73000e+02, 9.22852e-01, 0.00000e+00],
        [6.11000e+02, 2.53750e+02, 7.04000e+02, 3.85250e+02, 9.20410e-01, 1.00000e+00],
        [3.64750e+02, 2.52750e+02, 5.67500e+02, 8.71000e+02, 9.17480e-01, 0.00000e+00],
        [1.08400e+03, 4.47500e+01, 1.27400e+03, 5.56000e+02, 9.09668e-01, 0.00000e+00],
        [5.75000e+02, 1.25125e+02, 6.47000e+02, 2.23625e+02, 9.02832e-01, 1.00000e+00],
        [1.04100e+03, 2.87500e+02, 1.13900e+03, 4.21500e+02, 9.02832e-01, 1.00000e+00],
        [2.48500e+02, 2.85750e+02, 5.25500e+02, 8.75000e+02, 9.02344e-01, 0.00000e+00],
        [8.71250e+01, 1.02062e+02, 1.63875e+02, 1.93500e+02, 9.02344e-01, 1.00000e+00],
        [3.70750e+02, 3.20750e+02, 4.60250e+02, 4.40250e+02, 8.90137e-01, 1.00000e+00],
        [2.43500e+02, 7.71250e+01, 4.21500e+02, 4.65500e+02, 8.88672e-01, 0.00000e+00],
        [9.59500e+02, 1.12500e+02, 1.02050e+03, 1.89750e+02, 8.82324e-01, 1.00000e+00],
        [4.33000e+02, 2.60750e+02, 5.10500e+02, 3.53250e+02, 8.80371e-01, 1.00000e+00],
        [4.96500e+02, 1.21750e+02, 7.60500e+02, 6.88000e+02, 8.78418e-01, 0.00000e+00],
        [1.14000e+03, 5.07188e+01, 1.20400e+03, 1.21500e+02, 8.68164e-01, 1.00000e+00],
        [7.00000e+02, 1.46500e+02, 7.61000e+02, 2.19250e+02, 8.58398e-01, 1.00000e+00],
        [1.25000e+00, 9.67500e+01, 2.65250e+02, 7.53000e+02, 8.55469e-01, 0.00000e+00],
        [8.82500e+02, 1.07000e+02, 1.05600e+03, 5.72000e+02, 8.44727e-01, 0.00000e+00],
        [6.48000e+02, 1.42500e+02, 8.00000e+02, 5.63000e+02, 8.35938e-01, 0.00000e+00],
        [3.26562e+01, 3.77500e+02, 1.53250e+02, 5.59500e+02, 8.21777e-01, 1.00000e+00],
        [9.16000e+02, 9.22500e+01, 9.69000e+02, 1.54875e+02, 7.88574e-01, 1.00000e+00],
        [1.06100e+03, 5.35000e+01, 1.11700e+03, 1.25000e+02, 7.54395e-01, 1.00000e+00],
        [3.04500e+02, 2.22500e+01, 4.44500e+02, 4.13750e+02, 7.45605e-01, 0.00000e+00],
        [3.12500e+02, 8.26250e+01, 3.58500e+02, 1.43500e+02, 7.25586e-01, 1.00000e+00],
        [7.39500e+02, 4.72812e+01, 7.83500e+02, 1.01250e+02, 6.86523e-01, 1.00000e+00],
        [6.97000e+02, 4.10000e+01, 8.21000e+02, 4.34000e+02, 6.64551e-01, 0.00000e+00],
        [3.49500e+02, 2.06875e+01, 3.92500e+02, 6.88125e+01, 6.62109e-01, 1.00000e+00],
        [8.05500e+02, 1.92500e+01, 9.25500e+02, 3.87250e+02, 5.83008e-01, 0.00000e+00],
        [1.01850e+03, 4.86250e+01, 1.14800e+03, 4.28000e+02, 5.08789e-01, 0.00000e+00]], device='cuda:0')]

Detected Objects: 16 body, 16 head
```
 
 Neuron: 
 ```
 [tensor([[4.97000e+02, 3.40750e+02, 8.76000e+02, 1.28125e+03, 9.63478e-01, 0.00000e+00],
        [9.51625e+02, 3.99750e+02, 1.28038e+03, 1.27725e+03, 9.46970e-01, 0.00000e+00],
        [2.50000e-01, 5.18000e+02, 3.16750e+02, 1.27700e+03, 9.34893e-01, 0.00000e+00],
        [2.54250e+02, 3.96750e+02, 5.33250e+02, 1.28125e+03, 8.93420e-01, 0.00000e+00],
        [9.57125e+02, 2.95875e+02, 1.05088e+03, 4.49625e+02, 8.81106e-01, 1.00000e+00],
        [1.08019e+03, 3.75000e+01, 1.27581e+03, 7.13000e+02, 8.80013e-01, 0.00000e+00],
        [8.61562e+01, 1.25625e+02, 1.63969e+02, 2.45375e+02, 8.73601e-01, 1.00000e+00],
        [3.69000e+02, 4.64688e+02, 4.60000e+02, 6.01312e+02, 8.69089e-01, 1.00000e+00],
        [5.74000e+02, 1.58312e+02, 6.48000e+02, 2.98438e+02, 8.61382e-01, 1.00000e+00],
        [4.37500e+00, 1.18000e+02, 2.68375e+02, 9.92000e+02, 8.57389e-01, 0.00000e+00],
        [1.13781e+03, 4.60625e+01, 1.20419e+03, 1.31688e+02, 8.54140e-01, 1.00000e+00],
        [4.27812e+02, 3.60062e+02, 5.12688e+02, 4.90438e+02, 8.45462e-01, 1.00000e+00],
        [1.03791e+03, 4.22125e+02, 1.14209e+03, 5.77875e+02, 8.40414e-01, 1.00000e+00],
        [6.10156e+02, 3.53000e+02, 7.06844e+02, 5.08000e+02, 8.37262e-01, 1.00000e+00],
        [2.44062e+02, 8.80000e+01, 4.27938e+02, 6.38000e+02, 8.21898e-01, 0.00000e+00],
        [6.52125e+02, 1.80625e+02, 8.03875e+02, 6.67875e+02, 8.02543e-01, 0.00000e+00],
        [4.96000e+02, 1.54500e+02, 7.63000e+02, 9.19500e+02, 7.66319e-01, 0.00000e+00],
        [7.01625e+02, 1.87344e+02, 7.61375e+02, 2.73406e+02, 7.26700e-01, 1.00000e+00],
        [8.76625e+02, 1.25500e+02, 1.05638e+03, 7.00000e+02, 7.04233e-01, 0.00000e+00],
        [3.11297e+02, 9.46875e+01, 3.64703e+02, 1.69812e+02, 6.65033e-01, 1.00000e+00],
        [9.15641e+02, 1.07062e+02, 9.69359e+02, 1.76938e+02, 6.20309e-01, 1.00000e+00],
        [4.47188e+01, 5.35688e+02, 1.45656e+02, 6.65312e+02, 5.88628e-01, 1.00000e+00],
        [1.04012e+03, 5.00000e-01, 1.18988e+03, 3.23000e+02, 5.60488e-01, 0.00000e+00],
        [9.58031e+02, 1.39031e+02, 1.02097e+03, 2.32969e+02, 5.44382e-01, 1.00000e+00],
        [8.51250e+02, 9.78750e+01, 1.01275e+03, 5.58625e+02, 4.70551e-01, 0.00000e+00],
        [8.83000e+02, 3.34000e+02, 1.15300e+03, 1.29000e+03, 4.65154e-01, 0.00000e+00],
        [3.50266e+02, 7.67188e+00, 3.93234e+02, 5.94531e+01, 4.43892e-01, 1.00000e+00],
        [9.53250e+02, 2.59000e+02, 1.05275e+03, 5.00500e+02, 4.26359e-01, 0.00000e+00]])]

Detected Objects:  Body 14, Head 14
```
 
 Just in case I'm also attaching the script I'm using to convert the model:
 
 ```
import torch
import torch.neuron

def subgraph_builder_function(node):
  return 'YOLOLayer' not in node.name

model.load_state_dict(torch.load(weights,map_location=torch.device('cpu'))['model'])
model.eval()
fake_image = torch.zeros([1, 3, 1280, 1280], dtype=torch.float32)  
try:
  torch.neuron.trace(model, example_inputs=[fake_image],skip_compiler=True)
except Exception:
  torch.neuron.trace(model, example_inputs=[fake_image],skip_compiler=True)

#model_inspect = torch.neuron.trace(model, example_inputs=[fake_image],skip_compiler=True)
#print(model_inspect)

model_neuron = torch.neuron.trace(model, example_inputs=[fake_image])
#model_neuron = torch.neuron.trace(model, example_inputs=[fake_image],compiler_args=['--fast-math','fp32-cast-all-fp16'])
model_neuron.save('yolor_neuron_face_body.pt')  #Rename the model
 
 ```

**Comment by jluntamazon** [comment] 2022-07-12 23:03
This seems to be an issue that may be solved with some accuracy tuning. We have seen with this particular model (using the publicly available `yolor_p6.pt` weights) that the following flags produce the most accurate results:

```
compiler_args = "--fast-math no-fast-relayout --fp32-cast matmult-fp16"
```

The explanation behind this set of flags is that:
- Using `no-fast-relayout` preserves precision when changing the tensor orientation. Transposes may be inserted without explicitly being called from the framework code.
- Using `matmult-fp16` prioritizes numerical precision over dynamic range in matmult operations. This tends to perform better when conv/linear weights are small.
- Using `matmult-fp16` ensures that only matmult operations are downcast and activation/vector operations maintain 32-bit precision.
- Removing `fp32-cast-all-fp16` ensures that we preserve 32-bit precision for activation/vector operations. Otherwise these can be unnecessarily downcast.


There are more explanations of the individual casting options in the compiler CLI guide:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-cc/command-line-reference.html#cmdoption-neuron-cc-arg-0

And more explanations regarding mixed-precision in the following documentation:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/appnotes/perf/mixed-precision.html#mixed-precision

Please let us know if these flags resolve your accuracy issues.

**Comment by alejoGT1202** [comment] 2022-07-13 11:03
I tried with the flags you recommend me but unfortunately there were no improvements in accuracy. May I ask if you are converting the entire model? And what versions of Pytorch and neuron-cc are you using? Currently I'm using the following versions: 

```
Neuron Compiler version 1.11.4.0+97f99abe4

HWM version 1.11.0.0-0
NEFF version Dynamic
TVM version 1.11.0.0+0
NumPy version 1.19.5
MXNet not available
TF not available
```

`Pytorch: 1.10.1+cu102`

**Comment by jluntamazon** [comment] 2022-07-13 22:39
> And what versions of Pytorch and neuron-cc are you using?

The only difference between our testing environment version and yours is the pytorch version. The compilers flag were tested against the latest in the YoloR repository and `torch==1.11.0`. The pytorch version is likely not the reason for the accuracy differences. It is more likely to be weight/threshold dependent. Neuron will produce small differences in output values due to mixed precision. For sensitive thresholds (either NMS IoU or confidence thresholds), this can produce slightly different classifications.

> May I ask if you are converting the entire model?

Here is an example of tracing and inference (assumed to be executed from within the YoloR repository directory with a downloaded `yolor_p6.pt` file):

```python
import torch
import torch_neuron
from torchvision.transforms import functional
import PIL

# YoloR
from models.models import Darknet
from utils.general import non_max_suppression


def image(filename=None, batch_size=1, size=(256, 256)):

    if filename:
        image = PIL.Image.open(filename).convert('RGB')
        image = functional.resize(image, size)
        image = functional.to_tensor(image)
        image = torch.unsqueeze(image, 0)
        image = torch.repeat_interleave(image, batch_size, 0)
        return image

    return torch.ones(batch_size, 3, *size)


def load_model(size, checkpoint='yolor_p6.pt', configs='yolor_p6.cfg'):

    dev = torch.device('cpu')

    # Load & configure model weights
    model = Darknet(configs, (size, size)).to(dev)
    weights = torch.load(checkpoint, map_location=dev)['model']
    model.load_state_dict(weights)

    # Create a wrapper to only return the first result
    class Yolo(torch.nn.Module):
        def __init__(self, model) -> None:
            super().__init__()
            self.model = model

        def forward(self, image):
            return self.model(image)[0]

    model = Yolo(model)
    model.eval()

    return model


def trace(batch_size=1, size=256, device='neuron'):

    dev = torch.device('cpu' if device == 'neuron' else device)

    # Load model
    model = load_model(size)
    model.to(dev)

    # Create sample image
    example = image(batch_size=batch_size, size=(size, size))
    example.to(dev)

    # Execute once to configure
    model(example)

    # Trace
    if device == 'neuron':
        compiler_args = "--fast-math no-fast-relayout --fp32-cast matmult-fp16"
        # Note that fallback=False is used here to skip partitioning since all ops can be supported
        trace = torch_neuron.trace(model, example, fallback=False, compiler_args=compiler_args)
    else:
        trace = torch.jit.trace(model, example)

    # Serialize
    torch.jit.save(trace, f'model-b{batch_size}-s{size}-{device}.pt')


def infer(filename, batch_size=1, size=256, device='neuron'):

    dev = torch.device('cpu' if device == 'neuron' else device)

    with torch.no_grad():
        model = torch.jit.load(f'model-b{batch_size}-s{size}-{device}.pt')
        example = image(filename, batch_size=batch_size, size=(size, size))
        example.to(dev)
        result = model(example)
        preds = non_max_suppression(result)[0]

    boxes = preds[:, :4]
    classes = preds[:, 5].long()

    print("Boxes:")
    print(boxes)
    print()
    print('Classes:')
    print(classes)

    return result


if __name__ == '__main__':

    size = 1280
    batch_size = 1

    trace(batch_size=batch_size, size=size, device='cpu')
    trace(batch_size=batch_size, size=size, device='neuron')

    result_expect = infer(filename='inference/images/horses.jpg', batch_size=batch_size, size=size, device='cpu')
    result_actual = infer(filename='inference/images/horses.jpg', batch_size=batch_size, size=size, device='neuron')

    torch.testing.assert_allclose(result_actual, result_expect, rtol=0, atol=0)
```

Lastly, would you be able to provide the difference you see across the entire output tensor prior to NMS? You can easily check the differences with:

```python
import torch

result_expect = cpu_model(image_input)
result_actual = neuron_model(image_input)

torch.testing.assert_allclose(result_actual, result_expect, rtol=0, atol=0)
```

Also, If your tracing script looks significantly different, please let us know and we can look at what is causing the error.

**Comment by alejoGT1202** [comment] 2022-07-20 12:31
Here is the script I'm using to trace and infer the model. 

```
import torch
import torch.neuron
from utils.general import non_max_suppression

def subgraph_builder_function(node):
 return 'YOLOLayer' not in node.name

model.load_state_dict(torch.load(weights,map_location=torch.device('cpu'))['model'])
model.eval()
fake_image = torch.zeros([1, 3, 1280, 1280], dtype=torch.float32)  
try:
 torch.neuron.trace(model, example_inputs=[fake_image],skip_compiler=True)
except Exception:
 torch.neuron.trace(model, example_inputs=[fake_image],skip_compiler=True)

#model_inspect = torch.neuron.trace(model, example_inputs=[fake_image],skip_compiler=True)
#print(model_inspect)

model_neuron = torch.neuron.trace(model, example_inputs=[fake_image])
#model_neuron = torch.neuron.trace(model, example_inputs=[fake_image],compiler_args=['--fast-math','fp32-cast-all-fp16'])
model_neuron.save('yolor_neuron_face_body.pt')  #Rename the model

model = torch.jit.load('yolor_neuron.pt')
example = image('horses.jpg', batch_size=1 size=(1028,1028))
result = model(example)
pred = non_max_suppression(result,conf_thres=0.1,iou_thres=0.3,classes=None, agnostic= False)[0]

for i,det in enumerate(pred):
      data = det.numpy()
      x = int(data[0])
      y = int(data[1]) - 2  
      w = int(data[2])-x 
      h = int(data[3])-y 
     
      print("Coords")
      print(x, y, w, h)
      print("Score")
      print(data[4])
      print("Class")
      print(int(data[5]))


```
And the results I'm getting here I compared to the ones generated with the detection.py script from yoloR executed with the following flags: 

`python3 detection.py --source horses.jpg --cfg cfg/yolor_w6.cfg --weights weights/yolor_w6.pt --conf 0.3 --img-size 1280 --device cpu --save-txt`

**Comment by fishuke** [comment] 2022-08-18 10:36
@alejoGT1202 Have you tried this:

```python
for m in model.modules():
    if hasattr(m, 'inplace'):
        m.inplace = False
```

**Comment by alejoGT1202** [comment] 2022-08-31 13:22
Hi @fishuke I tried to implement it but unfortunately I'm getting the same results, thanks for the advice.

**Comment by hannanjgaws** [comment] 2022-09-09 22:13
Hi @alejoGT1202: 

We noticed you’re using `iou_thres=0.3` in your script in which you trace and infer the model on Neuron. However, based on your `python3 detection.py --source horses.jpg --cfg cfg/yolor_w6.cfg --weights weights/yolor_w6.pt --conf 0.3 --img-size 1280 --device cpu --save-txt` non-traced model  command, it looks like you’re using the default `iou_thres` value, which is `0.5` in `detect.py`.

Can you try using the same `iou_thres` value in all of your tests to see if the problem goes away?

**Comment by alejoGT1202** [comment] 2022-09-21 10:56
Hello @hannanjgaws  

I ran the tests again using same values for `iou_thresh ` but the issue is still there.

**Comment by aws-mvaria** [comment] 2022-09-27 16:36
Hi @alejoGT1202 ,

Perhaps we can speed up this process by speaking more directly. Please reach out to us at [aws-neuron-support@amazon.com](mailto:aws-neuron-support@amazon.com) and we can see how to help.

**Comment by jluntamazon** [comment] 2022-12-27 17:43
For record keeping purposes, the root cause was a difference in  the`Darknet` constructor size parameter. This ended up causing significantly different predictions on CPU vs Neuron.

@alejoGT1202
I will close this ticket for now, but feel free to open a new one if you run into any other issues

**Closed by jluntamazon** 2022-12-27 17:43 UTC
