### ISSUE TITLE
An Internal Compiler Error has occurred due to print sliced tensor

### ISSUE THREAD

**Issue by DaeyangCho** [aws-neuron/aws-neuron-sdk#773] opened 2023-10-25 02:18 UTC
Hi, I'm trying to compile my model using neuron.
My model uses python list a lot and there are lots of tensor slicing.
As a result, I am having difficulty compiling the model, and am trying to compile the model in smaller pieces.

Meanwhile, I encounterd the internal compile error when I printed a sliced ​​tensor.
Here is the sample code.

```
import torch
import torch.nn as nn
import torch_neuron

class Block(nn.Module):
    def forward(self, x, w):
        # when we comment out this print function, compile succeeds.
        print(f"x: {x.size()}. w: {w.size()}")
        x = x + 1
        return x

class MyModel(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.block = Block()

    def forward(self, x, w):
        x = self.block(x, w[:, 0:2, :])
        return x


x = torch.ones([1, 4, 4])
w = torch.ones([1, 4, 4])
model = MyModel()
model.eval()

torch.neuron.analyze_model(model, example_inputs=[x, w])
model_neuron = torch.neuron.trace(model, example_inputs=[x, w])
model_neuron.save('neuron.pt')
print("Neuron compile success")
```

Additionally, I would appreciate it if you could let me know if there is anything to keep in mind when using tensor slicing and python list.

**Comment by mrnikwaws** [comment] 2023-10-25 22:22
Thanks for reporting the issue.  I can reproduce the failure and we'll start investigating internally

**Comment by mrnikwaws** [comment] 2023-10-25 22:42
The issue seems to be not the slice, but that the `w` variable is not used in the internal Block class forward method.  Try this:

```
import torch
import torch.nn as nn
import torch_neuron

class Block(nn.Module):
    def forward(self, x, w):
        # when we comment out this print function, compile succeeds.
        print(f"x: {x.size()}. w: {w.size()}")
        x = x + w
        return x

class MyModel(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.block = Block()

    def forward(self, x, w):
        y = w[:, 0:4, :]
        out = self.block(x, y)
        return out


x = torch.ones([1, 4, 4])
w = torch.ones([1, 8, 4])
model = MyModel()
model.eval()

torch.neuron.analyze_model(model, example_inputs=[x, w])
model_neuron = torch.neuron.trace(model, example_inputs=[x, w])
model_neuron.save('neuron.pt')
print("Neuron compile success")

print(model(x,w))
```

**Comment by mrnikwaws** [comment] 2023-10-25 22:43
Most likely this messes with the way tensors are sent to compiled code.  Please respond if this does not fix your issue.

**Comment by DaeyangCho** [comment] 2023-10-26 07:33
Thanks for the reply!
Is there a page that summarizes things to keep in mind when compiling, such as an error occurring if the tensor passed as an argument is not used?

**Comment by mrnikwaws** [comment] 2023-10-30 17:25
We do have a troubleshooting section for inference here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuron/troubleshooting-guide.html#pytorch-neuron-inference-troubleshooting, however I don't think this case is covered.

**Comment by mrnikwaws** [comment] 2023-10-30 17:34
I'm going to close this ticket since it seems to be resolved, and I'll ping the appropriate folks offline on improvements.  Please open another ticket if you have other issues.

**Closed by mrnikwaws** 2023-10-30 17:34 UTC
Labels: documentation

**Comment by DaeyangCho** [comment] 2023-11-01 00:49
Thanks to your help I was able to compile my model.
From a newbie's perspective, I think these little tips can be of great help :)
