### ISSUE TITLE
Single Shard Transformer Benchmark 3x Slower on SDK 2.15

### ISSUE THREAD

**Issue by xanderdunn** [aws-neuron/aws-neuron-sdk#777] opened 2023-10-27 22:19 UTC
We warm up, then execute the graph 20 times and average the execution time.

Transformer (seq, n_layers, d_model, n_heads) = (2048, 1, 4608, 72):
SDK 2.14, neuronx-cc 2.10: 0.08560s
SDK 2.15, neuronx-cc 2.11: 0.27238s

Compiling with:
```
neuronx-cc compile /mnt/drive1/tmp/rust_hlo_transformer_xla_benchmark.pb --framework=XLA --target=trn1 --model-type=transformer --optlevel=3 --output /mnt/drive1/tmp/transformer_xla_benchmark_10328974149972011728.neff
```
The `--optlevel=3` flag has no effect on the times.

This is the same graph that experienced a performance regression in #692. 
Is it possible to add this graph to your performance regression testing suite so that we do not make regressions again with future releases?
[rust_hlo_transformer_xla_benchmark_4608.pb.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/13193673/rust_hlo_transformer_xla_benchmark_4608.pb.zip)

Latest:
```
$ neuronx-cc --version
NeuronX Compiler version 2.11.0.34+c5231f848

Python version 3.8.10
HWM version 2.11.0.2-e34678757
NumPy version 1.22.4

Running on AMI ami-01257e71ecb2f431c
Running in region usw2-az4
```

**Comment by jluntamazon** [comment] 2023-10-31 16:37
Hello,

We are looking into this issue and debugging potential root causes

**Comment by aws-donkrets** [comment] 2024-05-27 22:35
Hi [xanderdunn](https://github.com/xanderdunn) - we have identified a fix for this issue and expect it to be in our next (SDK 2.19) release

**Closed by aws-donkrets** 2024-05-27 22:35 UTC
Labels: performance, compiler
