### ISSUE TITLE
Model Compiling Error 

### ISSUE THREAD

**Issue by ndenStanford** [aws-neuron/aws-neuron-sdk#485] opened 2022-09-11 06:09 UTC
Dear AWS team, 

I am encountering an error when trying to trace the model. Such failure only occurs in some machines and not others. Interestingly, the torch and torch-neuron are the same across the machines. Would you mind letting us know what we should be looking at? I also attached an error log here. 

Thank you for your time and attention to this matter

```
INFO:Neuron:There are 2 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:There are 2 ops of 1 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 249, fused = 242, percent fused = 97.19%
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 249, fused = 242, percent fused = 97.19%
INFO:Neuron:Number of neuron graph operations 672 did not match traced graph 646 - using heuristic matching of hierarchical information
INFO:Neuron:Number of neuron graph operations 672 did not match traced graph 646 - using heuristic matching of hierarchical information
INFO:Neuron:Compiler args type is <class 'str'> value is -O2
INFO:Neuron:Compiler args type is <class 'str'> value is -O2
INFO:Neuron:Compiling function _NeuronGraph$275 with neuron-cc
INFO:Neuron:Compiling function _NeuronGraph$275 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/neuron-cc compile /tmp/tmpqz8j5gta/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqz8j5gta/graph_def.neff --io-config {"inputs": {"0:0": [[1, 50, 768], "float32"], "1:0": [[1, 50], "int64"]}, "outputs": ["Linear_16/aten_linear/Add:0"]} -O2 --verbose 35'
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/neuron-cc compile /tmp/tmpqz8j5gta/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqz8j5gta/graph_def.neff --io-config {"inputs": {"0:0": [[1, 50, 768], "float32"], "1:0": [[1, 50], "int64"]}, "outputs": ["Linear_16/aten_linear/Add:0"]} -O2 --verbose 35'
INFO:Neuron:Compile command returned: 1
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$275; falling back to native python function call
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$275; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/neuron-cc compile /tmp/tmpqz8j5gta/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqz8j5gta/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 50, 768], "float32"], "1:0": [[1, 50], "int64"]}, "outputs": ["Linear_16/aten_linear/Add:0"]}' -O2 --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch_neuron/convert.py", line 382, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch_neuron/decorators.py", line 220, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/neuron-cc compile /tmp/tmpqz8j5gta/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqz8j5gta/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 50, 768], "float32"], "1:0": [[1, 50], "int64"]}, "outputs": ["Linear_16/aten_linear/Add:0"]}' -O2 --verbose 35
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/neuron-cc compile /tmp/tmpqz8j5gta/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqz8j5gta/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 50, 768], "float32"], "1:0": [[1, 50], "int64"]}, "outputs": ["Linear_16/aten_linear/Add:0"]}' -O2 --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch_neuron/convert.py", line 382, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch_neuron/decorators.py", line 220, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/neuron-cc compile /tmp/tmpqz8j5gta/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpqz8j5gta/graph_def.neff --io-config '{"inputs": {"0:0": [[1, 50, 768], "float32"], "1:0": [[1, 50], "int64"]}, "outputs": ["Linear_16/aten_linear/Add:0"]}' -O2 --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 249, compiled = 0, percent compiled = 0.0%
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 249, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 37 [supported]
INFO:Neuron: => aten::Int: 37 [supported]
INFO:Neuron: => aten::add: 13 [supported]
INFO:Neuron: => aten::add: 13 [supported]
INFO:Neuron: => aten::contiguous: 6 [supported]
INFO:Neuron: => aten::contiguous: 6 [supported]
INFO:Neuron: => aten::div: 6 [supported]
INFO:Neuron: => aten::div: 6 [supported]
INFO:Neuron: => aten::dropout: 14 [supported]
INFO:Neuron: => aten::dropout: 14 [supported]
INFO:Neuron: => aten::embedding: 2 [not supported]
INFO:Neuron: => aten::embedding: 2 [not supported]
INFO:Neuron: => aten::eq: 6 [supported]
INFO:Neuron: => aten::eq: 6 [supported]
INFO:Neuron: => aten::expand_as: 6 [supported]
INFO:Neuron: => aten::expand_as: 6 [supported]
INFO:Neuron: => aten::gelu: 6 [supported]
INFO:Neuron: => aten::gelu: 6 [supported]
INFO:Neuron: => aten::layer_norm: 13 [supported]
INFO:Neuron: => aten::layer_norm: 13 [supported]
INFO:Neuron: => aten::linear: 38 [supported]
INFO:Neuron: => aten::linear: 38 [supported]
INFO:Neuron: => aten::masked_fill: 6 [supported]
INFO:Neuron: => aten::masked_fill: 6 [supported]
INFO:Neuron: => aten::matmul: 12 [supported]
INFO:Neuron: => aten::matmul: 12 [supported]
INFO:Neuron: => aten::relu: 1 [supported]
INFO:Neuron: => aten::relu: 1 [supported]
INFO:Neuron: => aten::select: 1 [supported]
INFO:Neuron: => aten::select: 1 [supported]
INFO:Neuron: => aten::size: 13 [supported]
INFO:Neuron: => aten::size: 13 [supported]
INFO:Neuron: => aten::slice: 3 [supported]
INFO:Neuron: => aten::slice: 3 [supported]
INFO:Neuron: => aten::softmax: 6 [supported]
INFO:Neuron: => aten::softmax: 6 [supported]
INFO:Neuron: => aten::transpose: 30 [supported]
INFO:Neuron: => aten::transpose: 30 [supported]
INFO:Neuron: => aten::view: 30 [supported]
INFO:Neuron: => aten::view: 30 [supported]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-e2bfecc4e2ab> in <module>
      2 optimize = "aggressive"
      3 
----> 4 model_neuron = torch_neuron.trace(model, example_inputs=neuron_inputs, compiler_args=compiler_options, optimize = optimize, strict=False)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    182         logger.debug("skip_inference_context - trace with fallback at {}".format(get_file_and_line()))
    183         neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 184     cu.stats_post_compiler(neuron_graph)
    185 
    186     # Wrap the compiled version of the model in a script module. Note that this is

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch_neuron/convert.py in stats_post_compiler(self, neuron_graph)
    491         if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
    492             raise RuntimeError(
--> 493                 "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    494 
    495         if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

**Comment by jeffhataws** [comment] 2022-09-12 14:17
Hi @ndenStanford,

To help you further, we will need more information about the instance type, OS, and installed packages, and the script that you use to compile. 

Also, please try adding option compiler_workdir="./workdir" in torch.neuron.trace command, like :

`model_neuron = torch.neuron.trace(model, compiler_workdir="./workdir", example_inputs=[fake_image])
`

During compilation, you will see informational message that points to the compiler log where you will be able to see more details about the compiler failure:

`INFO:Neuron:Compiling function _NeuronGraph$1441 with neuron-cc; log file is at /home/ubuntu/model/workdir/0/graph_def.neuron-cc.log`

**Comment by ndenStanford** [comment] 2022-09-12 16:42
Hello, 

Instance type: inf.6xlarge 
OS: ubuntu
Installed packages: pytorch-neuron, pytorch

I followed your recommendation by adding a compiler_workdir option. I'm seeing error messages in the following files. 

log-neuron-cc.txt
```
09/12/2022 03:57:52 PM ERROR 5310 [neuron-cc]: Failed to parse model /home/ubuntu/datascience/document_classification/app/workdir/26/graph_def.pb: The following operators are not implemented: {'SelectV2'} (NotImplementedError)
09/12/2022 04:32:32 PM ERROR 9214 [neuron-cc]: Failed to parse model /home/ubuntu/datascience/document_classification/app/workdir/26/graph_def.pb: The following operators are not implemented: {'SelectV2'} (NotImplementedError)
```

graph_def.neuron-cc.log
```
.09/12/2022 04:32:32 PM ERROR 9214 [neuron-cc]: Failed to parse model /home/ubuntu/datascience/document_classification/app/workdir/26/graph_def.pb: The following operators are not implemented: {'SelectV2'} (NotImplementedError)

Compiler status ERROR
Compiling with command line: '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/neuron-cc compile /home/ubuntu/datascience/document_classification/app/workdir/26/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/ubuntu/datascience/document_classification/app/workdir/26/graph_def.neff --io-config {"inputs": {"0:0": [[1, 50, 768], "float32"], "1:0": [[1, 50], "int64"]}, "outputs": ["Linear_16/aten_linear/Add:0"]} -O2 --verbose 35'
```

**Comment by jeffhataws** [comment] 2022-09-12 17:52
Thanks @ndenStanford . This is very helpful.

Can you validate that you installed the correct version of tensorflow on the new machine? Running the command:
`pip list | grep tensorflow `

Should show TensorFlow version 1.15.0

To ensure that you have installed the correct version, you can run:

`pip install --upgrade --force-reinstall --extra-index-url=https://pip.repos.neuron.amazonaws.com/ "neuron-cc[tensorflow]"`

**Comment by ndenStanford** [comment] 2022-09-12 18:20
Thank you for your advice. Turned out that my TensorFlow version did not match the one you stated. When I ran the command you suggested, I'm seeing the following errors. However, installing TensorFlow individually solved a problem! Is there a document that I can reference on the compatible TensorFlow version?

```
Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/commands.py", line 280, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
        _compile_single_file, objects)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 268, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 657, in get
        raise self._value
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 121, in worker
        result = (True, func(*args, **kwds))
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cbdpibdj/grpcio/setup.py", line 559, in <module>
        cmdclass=COMMAND_CLASS,
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/commands.py", line 285, in build_extensions
        "Failed `build_ext` step:\n{}".format(formatted_exception))
    commands.CommandError: Failed `build_ext` step:
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/commands.py", line 280, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
        _compile_single_file, objects)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 268, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 657, in get
        raise self._value
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 121, in worker
        result = (True, func(*args, **kwds))
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/tmp/pip-build-cbdpibdj/grpcio/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command '/home/ubuntu/anaconda3/envs/pytorch_latest_p37/bin/x86_64-conda-linux-gnu-cc' failed with exit status 1
    
    
    ----------------------------------------
  Rolling back uninstall of grpcio
Command "/home/ubuntu/airpr_crawler/aws_lambda/missing_sentiment/sentiment-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cbdpibdj/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-iwm0fi61-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cbdpibdj/grpcio/
```

**Comment by mrnikwaws** [comment] 2022-09-13 21:16
Hi @ndenStanford,

I'll take a look and see if I can reproduce that failure.  The install command 

```
pip install neuron-cc[tensorflow] 
```

is intended to take care of the install versioning.  This should be equivalent to:

```
pip install neuron-cc tensorflow==1.15.0
```

Older versions of tensorflow (<2) make use ahead of time graph construction that we leverage when we compile the pytorch model to our compiler.  This is intended to be an implementation detail (and should not affect our customers) which is why it isn't in our docs.  It looks like in your case pip experienced a "snarl up" when it tried to remove dependent packages.

I'm glad to see the problem is resolved!  I'll close this ticket since it looks like you are unblocked - but please re-open it if we can help out more.

**Closed** 2022-09-13 21:51 UTC

**Comment by ndenStanford** [comment] 2022-09-14 14:20
Thank you very much for your help. Would love to hear back if you can reproduce the issue with installation in case it becomes an issue in the future.
