### ISSUE TITLE
outputs are all "nan" when compiled model loaded from checkpoint

### ISSUE THREAD

**Issue by jestiny0** [aws-neuron/aws-neuron-sdk#612] opened 2022-12-06 09:12 UTC
I tried to compile an existed model, but encountered some problems.

### How to reproduce:

The simplified code:
```
net = Net()
device = torch.device('cpu')
net.to(device)
net.eval()

num_batches = 10
batch_size = 50
sequence_length = 80
batches = generate_random_batches(num_batches, sequence_length, batch_size)
logging.info(f"Generated random data with {num_batches} batches and batch size {batch_size} and sequence length {sequence_length}")

torch.neuron.analyze_model(net, example_inputs=[batches[0]])
inf_m = torch.neuron.trace(
    net, 
    example_inputs=[batches[0]], 
    compiler_workdir="./workdir", 
    dynamic_batch_size=True
)

inf_m.eval()

print(inf_m(batches[1]))
print(net(batches[1]))
```

outputs:
```
tensor([[-0.6931, -0.6936],
        [-0.6853, -0.7036],
        [-0.7578, -0.6328],
        [-0.5947, -0.8071],
        [-0.7314, -0.6533],
        [-0.4661, -0.9783],
        [-0.6774, -0.7145],
        [-0.7706, -0.6202],
        [-0.5139, -0.9114],
        [-0.8409, -0.5596],
        [-0.6328, -0.7558],
        [-0.5461, -0.8669],
        [-0.4513, -1.0099],
        [-0.5596, -0.8545],
        [-0.7978, -0.5947],
        [-0.4903, -0.9493],
        [-0.8371, -0.5685],
        [-0.7047, -0.6774],
        [-0.6451, -0.7428],
        [-0.7706, -0.6202],
        [-0.6033, -0.7864],
        [-0.6533, -0.7392],
        [-0.5461, -0.8674],
        [-0.6774, -0.7145],
        [-0.4210, -1.0655],
        [-0.8131, -0.5860],
        [-0.5506, -0.8563],
        [-0.9056, -0.5232],
        [-0.4002, -1.1092],
        [-0.3791, -1.1486],
        [-0.4158, -1.0672],
        [-0.6369, -0.7560],
        [-0.8519, -0.5506],
        [-0.7200, -0.6614],
        [-0.6033, -0.7947],
        [-0.6533, -0.7392],
        [-0.6451, -0.7491],
        [-0.5860, -0.8116],
        [-0.6774, -0.7038],
        [-0.6369, -0.7536],
        [-0.6533, -0.7285],
        [-0.5139, -0.9036],
        [-0.6734, -0.7125],
        [-0.5232, -0.8898],
        [-0.6160, -0.7757],
        [-0.5860, -0.8087],
        [-0.5416, -0.8678],
        [-0.4463, -1.0186],
        [-0.4758, -0.9768],
        [-0.3575, -1.2012]])
tensor([[-0.6925, -0.6938],
        [-0.6831, -0.7033],
        [-0.7575, -0.6327],
        [-0.5906, -0.8074],
        [-0.7287, -0.6588],
        [-0.4700, -0.9808],
        [-0.6749, -0.7117],
        [-0.7740, -0.6183],
        [-0.5136, -0.9122],
        [-0.8394, -0.5656],
        [-0.6353, -0.7545],
        [-0.5438, -0.8687],
        [-0.4522, -1.0112],
        [-0.5565, -0.8514],
        [-0.7976, -0.5986],
        [-0.4900, -0.9483],
        [-0.8339, -0.5698],
        [-0.7070, -0.6795],
        [-0.6475, -0.7409],
        [-0.7717, -0.6203],
        [-0.6083, -0.7859],
        [-0.6518, -0.7363],
        [-0.5455, -0.8664],
        [-0.6757, -0.7109],
        [-0.4221, -1.0662],
        [-0.8078, -0.5903],
        [-0.5485, -0.8624],
        [-0.9065, -0.5174],
        [-0.3990, -1.1116],
        [-0.3796, -1.1525],
        [-0.4197, -1.0707],
        [-0.6351, -0.7548],
        [-0.8565, -0.5528],
        [-0.7227, -0.6645],
        [-0.6010, -0.7947],
        [-0.6521, -0.7360],
        [-0.6411, -0.7480],
        [-0.5851, -0.8143],
        [-0.6826, -0.7038],
        [-0.6380, -0.7515],
        [-0.6569, -0.7307],
        [-0.5201, -0.9025],
        [-0.6780, -0.7085],
        [-0.5245, -0.8962],
        [-0.6164, -0.7763],
        [-0.5869, -0.8120],
        [-0.5453, -0.8667],
        [-0.4469, -1.0205],
        [-0.4738, -0.9745],
        [-0.3570, -1.2032]])
```

this code works well, although **the results are different** (let's talk about this later) .
But if I try to load checkpoint weights from trained model, all the outputs are "nan"

```
net = Net()
device = torch.device('cpu')

## the only difference
checkpoint_path = os.path.join(model_bin_dir, 'model.bin')
checkpoint = torch.load(checkpoint_path, map_location=device)
net.load_state_dict(checkpoint['model_state_dict'])

net.to(device)
net.eval()
```

outputs:
```
tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]])
```

--------

Besides, there are some error logs while compiling(In both cases above):
```
.12/06/2022 08:57:05 AM ERROR 24457 [IRVerifier]: incorrect axes in           float32 $431[i0_83_426,i1_83_426,i2_83_426] = tensor_contract_multiply_add(float32 $317[i0_83_426,i1_83_426,i2_83_426,i3_83_426], float32 $430[i0_83_426,i1_83_426,i2_83_426,i3_83_426], contract={i3_83_426=[0:266:1]}, lhs_free={i0_83_426=[0:50:1],i1_83_426=[0:80:1]}, rhs_free={i2_83_426=[0:40:1]}) # dl = Sequential_121/Linear_3/aten_linear/MatMul
12/06/2022 08:57:05 AM ERROR 24457 [IRVerifier]: incorrect axes in           float32 $458[i0_83_453,i1_83_453,i2_83_453] = tensor_contract_multiply_add(float32 $456[i0_83_453,i1_83_453,i2_83_453,i3_83_453], float32 $457[i0_83_453,i1_83_453,i2_83_453,i3_83_453], contract={i3_83_453=[0:266:1]}, lhs_free={i0_83_453=[0:50:1],i1_83_453=[0:80:1]}, rhs_free={i2_83_453=[0:40:1]}) # dl = Sequential_121/Linear_3/aten_linear/MatMul
12/06/2022 08:57:05 AM ERROR 24457 [IRVerifier]: incorrect axes in             float32 $468[i0_83_463,i1_83_463,i2_83_463] = tensor_contract_multiply_add(float32 $466[i0_83_463,i1_83_463,i2_83_463,i3_83_463_0,i3_83_463_1], float32 $467[i0_83_463,i1_83_463,i2_83_463,i3_83_463_0,i3_83_463_1], contract={i3_83_463_0=[0:3:1],i3_83_463_1=[0:16:1]}, lhs_free={i0_83_463=[0:50:1],i1_83_463=[0:80:1]}, rhs_free={i2_83_463=[0:40:1]}) # dl = Sequential_121/Linear_3/aten_linear/MatMul
12/06/2022 08:57:05 AM ERROR 24457 [IRVerifier]: incorrect axes in           float32 $478[i0_98_473,i1_98_473,i2_98_473] = tensor_contract_multiply_add(float32 $395[i0_98_473,i1_98_473,i2_98_473,i3_98_473], float32 $477[i0_98_473,i1_98_473,i2_98_473,i3_98_473], contract={i3_98_473=[0:266:1]}, lhs_free={i0_98_473=[0:50:1],i1_98_473=[0:80:1]}, rhs_free={i2_98_473=[0:40:1]}) # dl = Sequential_160/Linear_3/aten_linear/MatMul
12/06/2022 08:57:05 AM ERROR 24457 [IRVerifier]: incorrect axes in           float32 $505[i0_98_500,i1_98_500,i2_98_500] = tensor_contract_multiply_add(float32 $503[i0_98_500,i1_98_500,i2_98_500,i3_98_500], float32 $504[i0_98_500,i1_98_500,i2_98_500,i3_98_500], contract={i3_98_500=[0:266:1]}, lhs_free={i0_98_500=[0:50:1],i1_98_500=[0:80:1]}, rhs_free={i2_98_500=[0:40:1]}) # dl = Sequential_160/Linear_3/aten_linear/MatMul
12/06/2022 08:57:05 AM ERROR 24457 [IRVerifier]: incorrect axes in             float32 $515[i0_98_510,i1_98_510,i2_98_510] = tensor_contract_multiply_add(float32 $513[i0_98_510,i1_98_510,i2_98_510,i3_98_510_0,i3_98_510_1], float32 $514[i0_98_510,i1_98_510,i2_98_510,i3_98_510_0,i3_98_510_1], contract={i3_98_510_0=[0:3:1],i3_98_510_1=[0:16:1]}, lhs_free={i0_98_510=[0:50:1],i1_98_510=[0:80:1]}, rhs_free={i2_98_510=[0:40:1]}) # dl = Sequential_160/Linear_3/aten_linear/MatMul
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: ***************************************************************
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:  An Internal Compiler Error has occurred
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: ***************************************************************
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: 
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: Error message:  Incorrect IR by <class 'neuroncc.starfish.penguin.transforms.MemcpyElimination.MemcpyElimination'>
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: 
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: Error class:    AssertionError
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: Error location: Unknown
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: Command line:   /home/jiewang/.local/bin/neuron-cc compile /home/jiewang/nbcode/model-factory/pipelines/local_push_din_pipeline/local-din/nb-serving/workdir/156/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/jiewang/nbcode/model-factory/pipelines/local_push_din_pipeline/local-din/nb-serving/workdir/156/graph_def.neff --io-config '{"inputs": {"0:0": [[80, 5, 8], "float32"], "1:0": [[80, 5, 100], "float32"], "2:0": [[80, 5, 50], "float32"], "3:0": [[80, 5, 16], "float32"], "4:0": [[80, 32], "float32"], "5:0": [[80, 10], "float32"], "6:0": [[80, 50], "float32"], "7:0": [[80, 5, 8], "float32"], "8:0": [[80, 5, 100], "float32"], "9:0": [[80, 5, 50], "float32"], "10:0": [[80, 5, 16], "float32"], "11:0": [[80, 32], "float32"], "12:0": [[80, 10], "float32"], "13:0": [[80, 50], "float32"], "14:0": [[50, 5, 8], "float32"], "15:0": [[50, 5, 100], "float32"], "16:0": [[50, 5, 50], "float32"], "17:0": [[50, 5, 16], "float32"], "18:0": [[50, 32], "float32"], "19:0": [[50, 10], "float32"], "20:0": [[50, 50], "float32"], "21:0": [[1, 16], "float32"], "22:0": [[1, 16], "float32"], "23:0": [[50, 16], "float32"]}, "outputs": ["Ps_52/aten_cat_2/concat:0", "aten_expand/BroadcastTo:0", "aten_expand_1/BroadcastTo:0", "aten_expand_2/BroadcastTo:0", "aten_expand_3/BroadcastTo:0", "aten_expand_4/BroadcastTo:0", "Sequential_121/Linear_3/aten_linear/Add:0", "Sequential_160/Linear_3/aten_linear/Add:0"]}' --verbose 35
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: 
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: Internal details:
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/CommandDriver.py", line 224, in neuroncc.driver.CommandDriver.CommandDriver.run
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 576, in neuroncc.driver.commands.CompileCommand.CompileCommand.run
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 554, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 558, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 427, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 377, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 378, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 388, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 358, in neuroncc.driver.jobs.Frontend.Frontend.runTVMFrontend.tensorize
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 47, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 48, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 69, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/Compile.py", line 196, in neuroncc.starfish.penguin.Compile.compile_cu
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 380, in neuroncc.starfish.penguin.DotTransform.PassManager.transformFunction
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 134, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_or_rollback
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 178, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 160, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 186, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 188, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 189, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 334, in neuroncc.starfish.penguin.DotTransform.IterativeTransform.run_
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 335, in neuroncc.starfish.penguin.DotTransform.IterativeTransform.run_
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 348, in neuroncc.starfish.penguin.DotTransform.IterativeTransform.iterate
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 289, in neuroncc.starfish.penguin.DotTransform.DotTransform.transformFunction
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 275, in neuroncc.starfish.penguin.DotTransform.DotTransform.verify
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: 
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: Version information:
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   Neuron Compiler version 1.13.5.0+7dcf000a6
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   HWM version 1.13.0.0-0
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   NEFF version Dynamic
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   TVM version 1.13.0.0+0
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   NumPy version 1.18.5
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   MXNet not available
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]:   TF not available
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: 
12/06/2022 08:57:06 AM ERROR 24457 [neuron-cc]: Artifacts stored in: /home/jiewang/nbcode/model-factory/pipelines/local_push_din_pipeline/local-din/nb-serving/workdir/156

Compiler status ERROR
Compiling with command line: '/home/jiewang/.local/bin/neuron-cc compile /home/jiewang/nbcode/model-factory/pipelines/local_push_din_pipeline/local-din/nb-serving/workdir/156/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/jiewang/nbcode/model-factory/pipelines/local_push_din_pipeline/local-din/nb-serving/workdir/156/graph_def.neff --io-config {"inputs": {"0:0": [[80, 5, 8], "float32"], "1:0": [[80, 5, 100], "float32"], "2:0": [[80, 5, 50], "float32"], "3:0": [[80, 5, 16], "float32"], "4:0": [[80, 32], "float32"], "5:0": [[80, 10], "float32"], "6:0": [[80, 50], "float32"], "7:0": [[80, 5, 8], "float32"], "8:0": [[80, 5, 100], "float32"], "9:0": [[80, 5, 50], "float32"], "10:0": [[80, 5, 16], "float32"], "11:0": [[80, 32], "float32"], "12:0": [[80, 10], "float32"], "13:0": [[80, 50], "float32"], "14:0": [[50, 5, 8], "float32"], "15:0": [[50, 5, 100], "float32"], "16:0": [[50, 5, 50], "float32"], "17:0": [[50, 5, 16], "float32"], "18:0": [[50, 32], "float32"], "19:0": [[50, 10], "float32"], "20:0": [[50, 50], "float32"], "21:0": [[1, 16], "float32"], "22:0": [[1, 16], "float32"], "23:0": [[50, 16], "float32"]}, "outputs": ["Ps_52/aten_cat_2/concat:0", "aten_expand/BroadcastTo:0", "aten_expand_1/BroadcastTo:0", "aten_expand_2/BroadcastTo:0", "aten_expand_3/BroadcastTo:0", "aten_expand_4/BroadcastTo:0", "Sequential_121/Linear_3/aten_linear/Add:0", "Sequential_160/Linear_3/aten_linear/Add:0"]} --verbose 35'
```

And the compiled result:
```
WARNING:Neuron:torch.neuron.trace was unable to compile > 50% of the operators in the compiled model!
2022-12-06 09:03:42,222 : WARNING : torch.neuron.trace was unable to compile > 50% of the operators in the compiled model!
WARNING:Neuron:Please review the torch.neuron.analyze_model output and if you believe you are seeing a failure
2022-12-06 09:03:42,222 : WARNING : Please review the torch.neuron.analyze_model output and if you believe you are seeing a failure
WARNING:Neuron:Lodge an issue on https://github.com/aws/aws-neuron-sdk/issues if you believe the model is not compiling as expected
2022-12-06 09:03:42,222 : WARNING : Lodge an issue on https://github.com/aws/aws-neuron-sdk/issues if you believe the model is not compiling as expected
```
output of `torch.neuron.analyze_model`:
```
INFO:Neuron:93.75% of all operations (including primitives) (390 of 416) are supported
2022-12-06 09:03:13,769 : INFO : 93.75% of all operations (including primitives) (390 of 416) are supported
INFO:Neuron:79.69% of arithmetic operations (102 of 128) are supported
2022-12-06 09:03:13,769 : INFO : 79.69% of arithmetic operations (102 of 128) are supported
INFO:Neuron:There are 26 ops of 2 different types in the TorchScript that are not compiled by neuron-cc: aten::prelu, aten::embedding, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuron-cc/neuron-cc-ops/neuron-cc-ops-pytorch.html)
2022-12-06 09:03:15,265 : INFO : There are 26 ops of 2 different types in the TorchScript that are not compiled by neuron-cc: aten::prelu, aten::embedding, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/compiler/neuron-cc/neuron-cc-ops/neuron-cc-ops-pytorch.html)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 128, fused = 77, percent fused = 60.16%
2022-12-06 09:03:15,283 : INFO : Number of arithmetic operators (pre-compilation) before = 128, fused = 77, percent fused = 60.16%
```

### My problems:

1. **"nan" outputs**
2. possible causes of inconsistent outputs
3. possible causes of low successful op compiled rate

Thanks!

**Comment by jeffhataws** [comment] 2022-12-06 18:15
Hi @jestiny0,

Thank you for filing the issue.

A small amount of numerical mismatch in tensor outputs is expected for many applications due to our use of mixed precision. Are you noticing that your model’s final predictions are incorrect? If so, you can look at the [Mixed precision and performance-accuracy tuning (neuron-cc)](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/neuron-cc/mixed-precision.html) document to learn about compiler flags that can increase precision on Neuron.

Due to unsupported operators (likely aten::prelu) it appears that your graph is undergoing a worst-case graph partitioning. Support for aten::prelu is already a work in progress and will be available in a future release.
Without more information on this specific model, we cannot know if the NaN issues are caused by this poor partitioning behavior or some other factor. If you would like a more definitive answer prior to the release of aten::prelu support, are you able to share a model that reproduces the same compilation errors you’re seeing? Or, can you share your exact compilation artifacts with us privately at [aws-neuron-support@amazon.com](mailto:aws-neuron-support@amazon.com)?

**Comment by jestiny0** [comment] 2022-12-07 04:02
@jeffhataws 
Thanks for your helpful suggestions about [Mixed precision and performance-accuracy tuning (neuron-cc)](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/neuron-cc/mixed-precision.html). I've tried different flags, and lucky to see some flags such as `--fast-math fp32-cast-matmult` and `--fast-math none` can solve the "nan" problem. I will try to deploy the model serving service on inf firstly and if I have other questions I will back to fill the issue again.

**Comment by jeffhataws** [comment] 2022-12-08 15:58
@jestiny0 I am glad the solution worked for you. I will close this ticket for now but feel free to reopen or open new ticket if you have further issues. Thanks!

**Closed by jeffhataws** 2022-12-08 15:58 UTC
