### ISSUE TITLE
Neuron trace failed for a transformer-based text recognition model.

### ISSUE THREAD

**Issue by gavinkijkul** [aws-neuron/aws-neuron-sdk#410] opened 2022-03-17 10:06 UTC
## Code
I am trying to compile a text recognition model with neuron.
```
import os
import torch
from PIL import Image
import cv2
import numpy as np
import torch_neuron
from transformers import DeiTConfig, VisionEncoderDecoderConfig, VisionEncoderDecoderModel, AutoConfig

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Initializing a DeiT & XLM-ROBERTA style configuration
config_encoder = DeiTConfig(image_size=224)
config_encoder.return_dict = False

config_decoder = AutoConfig.from_pretrained('xlm-roberta-base')
config_decoder.return_dict = False

config = VisionEncoderDecoderConfig.from_encoder_decoder_configs(config_encoder, config_decoder)
config.return_dict = False

model = VisionEncoderDecoderModel(config=config)

model = model.encoder 
model.to(device)

# create dummy example inputs
img = Image.new('RGB', (224, 224))
pixel_values = processor(img, return_tensors="pt").pixel_values.to(device)
tokens_tensor = torch.ones([1, 512]).long()
segments_tensors = torch.ones([1, 512]).long()
dummy_enc_output = (torch.ones([1, 198, 768]), torch.ones([1, 768]))

model_neuron = torch.neuron.trace(model, [pixel_values, tokens_tensor, segments_tensors, dummy_enc_output])
```
## Error
I am getting this error. It says that all the operators are supported. Could you help explain what the error is and why it is happening? Is it the case that something in the model is not supported?
```
/home/ubuntu/anaconda3/envs/trocr/lib/python3.6/site-packages/torch/jit/_trace.py:991: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Tensor-likes are not close!

Mismatched elements: 127996361 / 128001024 (100.0%)
Greatest absolute difference: 2.1367889642715454 at index (0, 1, 71354) (up to 1e-05 allowed)
Greatest relative difference: inf at index (0, 25, 99747) (up to 1e-05 allowed)
  _module_class,
INFO:Neuron:There are 4 ops of 2 different types in the TorchScript that are not compiled by neuron-cc: aten::embedding, aten::repeat, (For more information see https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/neuron-cc-ops/neuron-cc-ops-pytorch.md)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 1072, fused = 1045, percent fused = 97.48%
/home/ubuntu/anaconda3/envs/trocr/lib/python3.6/site-packages/torch/jit/_trace.py:818: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Tensor-likes are not close!

Mismatched elements: 127996416 / 128001024 (100.0%)
Greatest absolute difference: 2.1944745779037476 at index (0, 24, 204917) (up to 1e-05 allowed)
Greatest relative difference: inf at index (0, 205, 136587) (up to 1e-05 allowed)
  _module_class,
INFO:Neuron:Compiling function _NeuronGraph$2123 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/trocr/bin/neuron-cc compile /tmp/tmp78fr_b60/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp78fr_b60/graph_def.neff --io-config {"inputs": {"3:0": [[512], "int64"], "4:0": [[1, 512, 512], "int64"], "tensor.11:0": [[1, 512], "int64"], "6:0": [[1, 512, 768], "float32"], "7:0": [[1, 512, 768], "float32"], "8:0": [[1, 512, 768], "float32"], "1:0": [[1, 198, 768], "float32"], "2:0": [[1, 768], "float32"]}, "outputs": ["Add_234:0", "transpose_2:0", "transpose_4:0", "transpose_11:0", "transpose_13:0", "transpose_22:0", "transpose_24:0", "transpose_31:0", "transpose_33:0", "transpose_42:0", "transpose_44:0", "transpose_51:0", "transpose_53:0", "transpose_62:0", "transpose_64:0", "transpose_71:0", "transpose_73:0", "transpose_82:0", "transpose_84:0", "transpose_91:0", "transpose_93:0", "transpose_102:0", "transpose_104:0", "transpose_111:0", "transpose_113:0", "transpose_122:0", "transpose_124:0", "transpose_131:0", "transpose_133:0", "transpose_142:0", "transpose_144:0", "transpose_151:0", "transpose_153:0", "transpose_162:0", "transpose_164:0", "transpose_171:0", "transpose_173:0", "transpose_182:0", "transpose_184:0", "transpose_191:0", "transpose_193:0", "transpose_202:0", "transpose_204:0", "transpose_211:0", "transpose_213:0", "transpose_222:0", "transpose_224:0", "transpose_231:0", "transpose_233:0", "1:0", "2:0"]} --verbose 35'
INFO:Neuron:Compile command returned: 1
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$2123; falling back to native python function call
ERROR:Neuron:neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/trocr/bin/neuron-cc compile /tmp/tmp78fr_b60/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp78fr_b60/graph_def.neff --io-config '{"inputs": {"3:0": [[512], "int64"], "4:0": [[1, 512, 512], "int64"], "tensor.11:0": [[1, 512], "int64"], "6:0": [[1, 512, 768], "float32"], "7:0": [[1, 512, 768], "float32"], "8:0": [[1, 512, 768], "float32"], "1:0": [[1, 198, 768], "float32"], "2:0": [[1, 768], "float32"]}, "outputs": ["Add_234:0", "transpose_2:0", "transpose_4:0", "transpose_11:0", "transpose_13:0", "transpose_22:0", "transpose_24:0", "transpose_31:0", "transpose_33:0", "transpose_42:0", "transpose_44:0", "transpose_51:0", "transpose_53:0", "transpose_62:0", "transpose_64:0", "transpose_71:0", "transpose_73:0", "transpose_82:0", "transpose_84:0", "transpose_91:0", "transpose_93:0", "transpose_102:0", "transpose_104:0", "transpose_111:0", "transpose_113:0", "transpose_122:0", "transpose_124:0", "transpose_131:0", "transpose_133:0", "transpose_142:0", "transpose_144:0", "transpose_151:0", "transpose_153:0", "transpose_162:0", "transpose_164:0", "transpose_171:0", "transpose_173:0", "transpose_182:0", "transpose_184:0", "transpose_191:0", "transpose_193:0", "transpose_202:0", "transpose_204:0", "transpose_211:0", "transpose_213:0", "transpose_222:0", "transpose_224:0", "transpose_231:0", "transpose_233:0", "1:0", "2:0"]}' --verbose 35
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/trocr/lib/python3.6/site-packages/torch_neuron/convert.py", line 387, in op_converter
    item, inputs, compiler_workdir=sg_workdir, **kwargs)
  File "/home/ubuntu/anaconda3/envs/trocr/lib/python3.6/site-packages/torch_neuron/decorators.py", line 221, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/trocr/bin/neuron-cc compile /tmp/tmp78fr_b60/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp78fr_b60/graph_def.neff --io-config '{"inputs": {"3:0": [[512], "int64"], "4:0": [[1, 512, 512], "int64"], "tensor.11:0": [[1, 512], "int64"], "6:0": [[1, 512, 768], "float32"], "7:0": [[1, 512, 768], "float32"], "8:0": [[1, 512, 768], "float32"], "1:0": [[1, 198, 768], "float32"], "2:0": [[1, 768], "float32"]}, "outputs": ["Add_234:0", "transpose_2:0", "transpose_4:0", "transpose_11:0", "transpose_13:0", "transpose_22:0", "transpose_24:0", "transpose_31:0", "transpose_33:0", "transpose_42:0", "transpose_44:0", "transpose_51:0", "transpose_53:0", "transpose_62:0", "transpose_64:0", "transpose_71:0", "transpose_73:0", "transpose_82:0", "transpose_84:0", "transpose_91:0", "transpose_93:0", "transpose_102:0", "transpose_104:0", "transpose_111:0", "transpose_113:0", "transpose_122:0", "transpose_124:0", "transpose_131:0", "transpose_133:0", "transpose_142:0", "transpose_144:0", "transpose_151:0", "transpose_153:0", "transpose_162:0", "transpose_164:0", "transpose_171:0", "transpose_173:0", "transpose_182:0", "transpose_184:0", "transpose_191:0", "transpose_193:0", "transpose_202:0", "transpose_204:0", "transpose_211:0", "transpose_213:0", "transpose_222:0", "transpose_224:0", "transpose_231:0", "transpose_233:0", "1:0", "2:0"]}' --verbose 35
INFO:Neuron:Number of arithmetic operators (post-compilation) before = 1072, compiled = 0, percent compiled = 0.0%
INFO:Neuron:The neuron partitioner created 1 sub-graphs
INFO:Neuron:Neuron successfully compiled 0 sub-graphs, Total fused subgraphs = 1, Percent of model sub-graphs successfully compiled = 0.0%
INFO:Neuron:Compiled these operators (and operator counts) to Neuron:
INFO:Neuron:Not compiled operators (and operator counts) to Neuron:
INFO:Neuron: => aten::Int: 199 [supported]
INFO:Neuron: => aten::ScalarImplicit: 1 [supported]
INFO:Neuron: => aten::add: 64 [supported]
INFO:Neuron: => aten::arange: 1 [supported]
INFO:Neuron: => aten::contiguous: 24 [supported]
INFO:Neuron: => aten::cumsum: 1 [supported]
INFO:Neuron: => aten::div: 24 [supported]
INFO:Neuron: => aten::dropout: 61 [supported]
INFO:Neuron: => aten::embedding: 3 [not supported]
INFO:Neuron: => aten::expand: 1 [supported]
INFO:Neuron: => aten::gelu: 13 [supported]
INFO:Neuron: => aten::layer_norm: 38 [supported]
INFO:Neuron: => aten::le: 1 [supported]
INFO:Neuron: => aten::linear: 122 [supported]
INFO:Neuron: => aten::matmul: 48 [supported]
INFO:Neuron: => aten::mul: 4 [supported]
INFO:Neuron: => aten::ne: 1 [supported]
INFO:Neuron: => aten::ones: 1 [supported]
INFO:Neuron: => aten::permute: 96 [supported]
INFO:Neuron: => aten::repeat: 1 [not supported]
INFO:Neuron: => aten::rsub: 2 [supported]
INFO:Neuron: => aten::size: 196 [supported]
INFO:Neuron: => aten::slice: 11 [supported]
INFO:Neuron: => aten::softmax: 24 [supported]
INFO:Neuron: => aten::to: 5 [supported]
INFO:Neuron: => aten::transpose: 24 [supported]
INFO:Neuron: => aten::type_as: 1 [supported]
INFO:Neuron: => aten::unsqueeze: 9 [supported]
INFO:Neuron: => aten::view: 96 [supported]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-5738c26c560c> in <module>
      1 # model_neuron = torch.neuron.trace(model, pixel_values, strict=False)
----> 2 model_neuron = torch.neuron.trace(model, [pixel_values, tokens_tensor, segments_tensors, dummy_enc_output])

~/anaconda3/envs/trocr/lib/python3.6/site-packages/torch_neuron/convert.py in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    165     with skip_inference_context() as s:
    166         neuron_graph = cu.compile_fused_operators(neuron_graph, **compile_kwargs)
--> 167     cu.stats_post_compiler(neuron_graph)
    168 
    169     # Wrap the compiled version of the model in a script module. Note that this is

~/anaconda3/envs/trocr/lib/python3.6/site-packages/torch_neuron/convert.py in stats_post_compiler(self, neuron_graph)
    496         if succesful_compilations == 0 and not self.allow_no_ops_on_neuron:
    497             raise RuntimeError(
--> 498                 "No operations were successfully partitioned and compiled to neuron for this model - aborting trace!")
    499 
    500         if percent_operations_compiled < 50.0:

RuntimeError: No operations were successfully partitioned and compiled to neuron for this model - aborting trace!
```

## Environment
inf1.6xlarge instance with Ubuntu DLAMI
```
spyder                             5.0.5                                                                                                                                                             [0/313]
spyder-kernels                     2.0.5
SQLAlchemy                         1.4.22
statsmodels                        0.12.2
sympy                              1.8
tables                             3.6.1
tblib                              1.7.0
tenacity                           8.0.1
tensorboard                        1.15.0
tensorflow                         1.15.0
tensorflow-estimator               1.15.1
termcolor                          1.1.0
terminado                          0.12.1
testpath                           0.5.0
textdistance                       4.2.2
threadpoolctl                      3.0.0
three-merge                        0.1.1
tifffile                           2020.6.3
tinycss2                           1.1.1
tokenizers                         0.11.6
toml                               0.10.2
tomli                              1.2.2
toolz                              0.11.2
torch                              1.10.1
torch-model-archiver               0.5.3
torch-neuron                       1.10.1.2.1.7.0
torch-workflow-archiver            0.2.3
torchserve                         0.5.3
torchvision                        0.11.2
tornado                            6.1
tqdm                               4.62.3
traitlets                          4.3.3
transformers                       4.17.0
typed-ast                          1.4.3
typing_extensions                  4.0.1
ujson                              4.0.2
unicodecsv                         0.14.1
urllib3                            1.26.8
watchdog                           2.1.6
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   1.2.3
Werkzeug                           2.0.2
wheel                              0.37.1
whichcraft                         0.6.1
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          3.0.2
xlrd                               2.0.1
XlsxWriter                         3.0.2
xlwt                               1.3.0
xxhash                             3.0.0
yapf                               0.32.0
yarl                               1.7.2
zict                               2.0.0
zipp                               3.7.0
zope.event                         4.5.0
zope.interface                     5.4.0
```

Thanks in advance!

**Comment by aws-diamant** [comment] 2022-03-21 01:40
Hi @gavinkijkul , and thanks for opening the ticket.
I'm working to reproduce this issue -> could you please share the code for 'processor' above?

Thanks,
Ron

**Comment by gavinkijkul** [comment] 2022-03-21 02:02
Thanks for the help @aws-diamant! Below is the code for 'processor'.

```
"""
Processor class for TrOCR.
"""
from contextlib import contextmanager
from transformers.feature_extraction_utils import FeatureExtractionMixin
from transformers.models.roberta.tokenization_roberta import RobertaTokenizer
from transformers.models.roberta.tokenization_roberta_fast import RobertaTokenizerFast
from transformers import AutoFeatureExtractor

class TrOCRProcessor:
    """
    Constructs a TrOCR processor which wraps a vision feature extractor and a TrOCR tokenizer into a single processor.

    [`TrOCRProcessor`] offers all the functionalities of [`AutoFeatureExtractor`]
    and [`RobertaTokenizer`]. See the [`~TrOCRProcessor.__call__`] and
    [`~TrOCRProcessor.decode`] for more information.

    Args:
        feature_extractor ([`AutoFeatureExtractor`]):
            An instance of [`AutoFeatureExtractor`]. The feature extractor is a required input.
        tokenizer ([`RobertaTokenizer`]):
            An instance of [`RobertaTokenizer`]. The tokenizer is a required input.
    """

    def __init__(self, feature_extractor, tokenizer):
        if not isinstance(feature_extractor, FeatureExtractionMixin):
            raise ValueError(
                f"`feature_extractor` has to be of type {FeatureExtractionMixin.__class__}, but is {type(feature_extractor)}"
            )
        # if not (isinstance(tokenizer, RobertaTokenizer) or (isinstance(tokenizer, RobertaTokenizerFast))):
        #     raise ValueError(
        #         f"`tokenizer` has to be of type {RobertaTokenizer.__class__} or {RobertaTokenizerFast.__class__}, but is {type(tokenizer)}"
        #     )

        self.feature_extractor = feature_extractor
        self.tokenizer = tokenizer
        self.current_processor = self.feature_extractor

    def save_pretrained(self, save_directory):
        """
        Save a TrOCR feature extractor object and TrOCR tokenizer object to the directory `save_directory`, so that
        it can be re-loaded using the [`~TrOCRProcessor.from_pretrained`] class method.

        <Tip>

        This class method is simply calling [`~PreTrainedFeatureExtractor.save_pretrained`] and
        [`~tokenization_utils_base.PreTrainedTokenizer.save_pretrained`]. Please refer to the
        docstrings of the methods above for more information.

        </Tip>

        Args:
            save_directory (`str` or `os.PathLike`):
                Directory where the feature extractor JSON file and the tokenizer files will be saved (directory will
                be created if it does not exist).
        """

        self.feature_extractor.save_pretrained(save_directory)
        self.tokenizer.save_pretrained(save_directory)

    @classmethod
    def from_pretrained(cls, pretrained_model_name_or_path, **kwargs):
        r"""
        Instantiate a [`TrOCRProcessor`] from a pretrained TrOCR processor.

        <Tip>

        This class method is simply calling AutoFeatureExtractor's
        [`~PreTrainedFeatureExtractor.from_pretrained`] and TrOCRTokenizer's
        [`~tokenization_utils_base.PreTrainedTokenizer.from_pretrained`]. Please refer to the
        docstrings of the methods above for more information.

        </Tip>

        Args:
            pretrained_model_name_or_path (`str` or `os.PathLike`):
                This can be either:

                - a string, the *model id* of a pretrained feature_extractor hosted inside a model repo on
                  huggingface.co. Valid model ids can be located at the root-level, like `bert-base-uncased`, or
                  namespaced under a user or organization name, like `dbmdz/bert-base-german-cased`.
                - a path to a *directory* containing a feature extractor file saved using the
                  [`~PreTrainedFeatureExtractor.save_pretrained`] method, e.g.,
                  `./my_model_directory/`.
                - a path or url to a saved feature extractor JSON *file*, e.g.,
                  `./my_model_directory/preprocessor_config.json`.
            **kwargs
                Additional keyword arguments passed along to both [`PreTrainedFeatureExtractor`] and
                [`PreTrainedTokenizer`]
        """
        feature_extractor = AutoFeatureExtractor.from_pretrained(pretrained_model_name_or_path, **kwargs)
        tokenizer = RobertaTokenizer.from_pretrained(pretrained_model_name_or_path, **kwargs)

        return cls(feature_extractor=feature_extractor, tokenizer=tokenizer)

    def __call__(self, *args, **kwargs):
        """
        When used in normal mode, this method forwards all its arguments to AutoFeatureExtractor's
        [`~AutoFeatureExtractor.__call__`] and returns its output. If used in the context
        [`~TrOCRProcessor.as_target_processor`] this method forwards all its arguments to
        TrOCRTokenizer's [`~TrOCRTokenizer.__call__`]. Please refer to the doctsring of the above two
        methods for more information.
        """
        return self.current_processor(*args, **kwargs)

    def batch_decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to TrOCRTokenizer's
        [`~PreTrainedTokenizer.batch_decode`]. Please refer to the docstring of this method for more
        information.
        """
        return self.tokenizer.batch_decode(*args, **kwargs)

    def decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to TrOCRTokenizer's [`~PreTrainedTokenizer.decode`].
        Please refer to the docstring of this method for more information.
        """
        return self.tokenizer.decode(*args, **kwargs)

    @contextmanager
    def as_target_processor(self):
        """
        Temporarily sets the tokenizer for processing the input. Useful for encoding the labels when fine-tuning TrOCR.
        """
        self.current_processor = self.tokenizer
        yield
        self.current_processor = self.feature_extractor

```

**Comment by gavinkijkul** [comment] 2022-03-21 02:04
Sorry for the incomplete code. Here is the rest.

```
from transformers import AutoTokenizer, AutoFeatureExtractor

feature_extractor = AutoFeatureExtractor.from_pretrained('facebook/deit-base-patch16-224')
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
processor = TrOCRProcessor(feature_extractor, tokenizer)

```

**Comment by hannanjgaws** [comment] 2022-04-28 14:32
Hi @gavinkijkul, 

Thank you for providing the scripts. We are able to reproduce the issue, and are actively working on a fix. We will keep you posted on our progress, and will let you know when the fix is released.

**Comment by aws-taylor** [comment] 2022-06-06 16:49
Hello @gavinkijkul,

  We are continuing to look at this issue, but the fix has not been incorporated into our release yet. We'll update this issue once it is available.

**Comment by mrnikwaws** [comment] 2022-09-14 14:33
Hi @gavinkijkul,

The issue has been root caused, and the fix is working its way through our release processes.  We will update this issue once the fix is available.

**Comment by awsrjh** [comment] 2022-11-28 20:58
Hi

we have released a fix for this in our latest release : 

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#neuron-2-5-0-11-23-2022

**Closed by awsrjh** 2022-11-28 20:58 UTC
